#!/usr/bin/env bash
set -euo pipefail

VERSION="${GITHUB_REF_NAME#v}"
TAG="${GITHUB_REF_NAME}"

mkdir -p /tmp/assets
gh release download "$TAG" -D /tmp/assets -p '*.tar.gz' -p '*.zip' || true

# Start formula
cat > /tmp/ax-code.rb << 'HEADER'
# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
HEADER

echo "  version \"${VERSION}\"" >> /tmp/ax-code.rb
echo "" >> /tmp/ax-code.rb
echo "  depends_on \"ripgrep\"" >> /tmp/ax-code.rb
echo "" >> /tmp/ax-code.rb

# macOS block
echo "  on_macos do" >> /tmp/ax-code.rb
cat >> /tmp/ax-code.rb << 'EOF'
    if Hardware::CPU.intel?
      odie "macOS Intel is not supported. ax-code supports macOS arm64 only."
    end
EOF
f="/tmp/assets/ax-code-darwin-arm64.zip"
if [ -f "$f" ]; then
  SHA=$(sha256sum "$f" | cut -d' ' -f1)
  cat >> /tmp/ax-code.rb << EOF
    if Hardware::CPU.arm?
      url "https://github.com/defai-digital/ax-code/releases/download/${TAG}/ax-code-darwin-arm64.zip"
      sha256 "${SHA}"
      def install
        bin.install "ax-code"
      end
    end
EOF
fi
echo "  end" >> /tmp/ax-code.rb
echo "" >> /tmp/ax-code.rb

# Linux block
echo "  on_linux do" >> /tmp/ax-code.rb
for arch in arm64 x64; do
  f="/tmp/assets/ax-code-linux-${arch}.tar.gz"
  if [ -f "$f" ]; then
    SHA=$(sha256sum "$f" | cut -d' ' -f1)
    if [ "$arch" = "arm64" ]; then CPU="arm?"; else CPU="intel?"; fi
    cat >> /tmp/ax-code.rb << EOF
    if Hardware::CPU.${CPU} and Hardware::CPU.is_64_bit?
      url "https://github.com/defai-digital/ax-code/releases/download/${TAG}/ax-code-linux-${arch}.tar.gz"
      sha256 "${SHA}"
      def install
        bin.install "ax-code"
      end
    end
EOF
  fi
done
echo "  end" >> /tmp/ax-code.rb
echo "end" >> /tmp/ax-code.rb

# Check if any platforms were found
if ! grep -q 'sha256' /tmp/ax-code.rb; then
  echo "::warning::No platform binaries found, skipping Homebrew update"
  exit 0
fi

echo "Generated formula:"
cat /tmp/ax-code.rb

# Push to tap repo
git clone "https://x-access-token:${GH_TOKEN}@github.com/defai-digital/homebrew-ax-code.git" /tmp/tap
cp /tmp/ax-code.rb /tmp/tap/ax-code.rb
cd /tmp/tap
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add ax-code.rb
if ! git diff --cached --quiet; then
  git commit -m "Update ax-code to v${VERSION}"
  git push
  echo "Homebrew tap updated to v${VERSION}"
else
  echo "Formula unchanged, skipping push"
fi
