#!/usr/bin/env bash
# Update the Homebrew tap with the default source+bun formula.
#
# The primary `ax-code` formula now installs the npm source distribution
# (`@defai.digital/ax-code`) and depends on Homebrew's bun runtime. This keeps
# brew users off the Bun `build --compile` binary path that triggers the TUI
# Worker hang class.
set -euo pipefail

VERSION="${GITHUB_REF_NAME#v}"
SOURCE_PACKAGE_PATH="@defai.digital/ax-code"
SOURCE_TARBALL_NAME="ax-code"
TARBALL_URL="https://registry.npmjs.org/${SOURCE_PACKAGE_PATH}/-/${SOURCE_TARBALL_NAME}-${VERSION}.tgz"

# Wait briefly for the npm registry to converge. The source publish job
# completes before this job runs, but the registry CDN can lag for a few
# seconds before the tarball is fetchable.
attempts=0
max_attempts=30
while ! curl -fsSL -o /tmp/ax-code.tgz "$TARBALL_URL"; do
  attempts=$((attempts + 1))
  if [ "$attempts" -ge "$max_attempts" ]; then
    echo "::error::source tarball not available at $TARBALL_URL after $max_attempts attempts"
    exit 1
  fi
  sleep 5
done

if command -v sha256sum >/dev/null 2>&1; then
  SHA="$(sha256sum /tmp/ax-code.tgz | cut -d' ' -f1)"
else
  SHA="$(shasum -a 256 /tmp/ax-code.tgz | cut -d' ' -f1)"
fi

cat > /tmp/ax-code.rb << HEADER
# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
#
# Default source-distribution formula for ax-code. Ships pre-bundled
# JavaScript and runs it with Homebrew's bun runtime, avoiding the
# bun build --compile × Worker bug class that affects the old compiled
# binary on some terminals (oven-sh/bun#26762, #27766, #29124).
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
  url "${TARBALL_URL}"
  sha256 "${SHA}"
  version "${VERSION}"
  license "MIT"

  depends_on "bun"
  depends_on "ripgrep"

  def install
    libexec.install Dir["*"]

    (bin/"ax-code").write <<~EOS
      #!/bin/sh
      AX_CODE_ORIGINAL_CWD="\$(pwd)" exec "#{Formula["bun"].opt_bin}/bun" "#{libexec}/bundle/index.js" "\$@"
    EOS
    (bin/"ax-code").chmod 0755
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
HEADER

echo "Generated formula:"
cat /tmp/ax-code.rb

git clone "https://x-access-token:${GH_TOKEN}@github.com/defai-digital/homebrew-ax-code.git" /tmp/tap
cp /tmp/ax-code.rb /tmp/tap/ax-code.rb
cd /tmp/tap
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add ax-code.rb
if ! git diff --cached --quiet; then
  git commit -m "Update ax-code to v${VERSION}"
  git push
  echo "Homebrew tap updated to v${VERSION}"
else
  echo "Formula unchanged, skipping push"
fi
