#!/usr/bin/env bash
# Update the Homebrew tap with the node-bundled formula.
#
# The primary `ax-code` formula tracks GitHub release assets produced by the
# tag-driven release workflow. Run this script manually after the GitHub
# release assets are available.
#
# Inputs (env):
#   GITHUB_REF_NAME — release tag (e.g. v5.5.1)
#   GH_TOKEN        — read access to the ax-code release assets
#   TAP_TOKEN       — legacy write token for the Homebrew tap repositories.
#   HOMEBREW_TAP_TOKEN — preferred write token for the shared and legacy taps.
#                    Local manual runs may fall back to GH_TOKEN when it has
#                    tap write access.
set -euo pipefail

VERSION="${GITHUB_REF_NAME#v}"
TAG="v${VERSION}"
RELEASE_BASE="https://github.com/defai-digital/ax-code/releases/download/${TAG}"
SOURCE_REPO="${GITHUB_REPOSITORY:-defai-digital/ax-code}"
MINISIGN_PUBLIC_KEY="${AX_CODE_MINISIGN_PUBLIC_KEY:-docs/release/ax-minisign.pub}"
RELEASE_READ_TOKEN="${GH_TOKEN:-}"
LEGACY_TAP_AUTH_TOKEN="${TAP_TOKEN:-}"
NAMED_TAP_AUTH_TOKEN="${HOMEBREW_TAP_TOKEN:-}"
TAP_AUTH_LABELS=()
TAP_AUTH_TOKENS=()

add_tap_token() {
  local label="$1"
  local token="$2"
  local existing

  if [ -z "${token}" ]; then
    return
  fi

  if [ "${#TAP_AUTH_TOKENS[@]}" -gt 0 ]; then
    for existing in "${TAP_AUTH_TOKENS[@]}"; do
      if [ "${existing}" = "${token}" ]; then
        return
      fi
    done
  fi

  TAP_AUTH_LABELS+=("${label}")
  TAP_AUTH_TOKENS+=("${token}")
}

if [ -z "${RELEASE_READ_TOKEN}" ]; then
  echo "::error::GH_TOKEN is required to read release assets from ${SOURCE_REPO}"
  exit 1
fi
if ! command -v minisign >/dev/null 2>&1; then
  echo "::error::minisign is required to verify release assets"
  exit 1
fi
if [ ! -f "${MINISIGN_PUBLIC_KEY}" ]; then
  echo "::error::pinned minisign public key not found: ${MINISIGN_PUBLIC_KEY}"
  exit 1
fi

# Prefer the legacy TAP_TOKEN first so existing tap-write credentials keep
# working even if the newer HOMEBREW_TAP_TOKEN secret is present but scoped
# incorrectly.
add_tap_token "TAP_TOKEN" "${LEGACY_TAP_AUTH_TOKEN}"
add_tap_token "HOMEBREW_TAP_TOKEN" "${NAMED_TAP_AUTH_TOKEN}"

if [ "${#TAP_AUTH_TOKENS[@]}" -eq 0 ]; then
  if [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    echo "::error::HOMEBREW_TAP_TOKEN is not configured; stable releases must update the Homebrew tap"
    exit 1
  fi
  add_tap_token "GH_TOKEN" "${GH_TOKEN:-}"
fi
if [ "${#TAP_AUTH_TOKENS[@]}" -eq 0 ]; then
  echo "::error::TAP_TOKEN, HOMEBREW_TAP_TOKEN, or a tap-write GH_TOKEN is required to update the Homebrew tap"
  exit 1
fi
# Keep release downloads on the source-repo token. The tap write token may be
# scoped only to defai-digital/homebrew-tap and can fail release reads with
# "Resource not accessible by personal access token".
export GH_TOKEN="${RELEASE_READ_TOKEN}"

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

download_asset() {
  local asset="$1"
  local dest="/tmp/${asset}"
  local attempts=0
  local max_attempts=30

  rm -f "${dest}"
  while ! gh release download "${TAG}" \
    --repo "${SOURCE_REPO}" \
    --pattern "${asset}" \
    --dir /tmp \
    --clobber; do
    attempts=$((attempts + 1))
    echo "::warning::Attempt ${attempts}/${max_attempts} failed for ${asset}; retrying in 5 seconds"
    if [ "$attempts" -ge "$max_attempts" ]; then
      echo "::error::release asset ${asset} not available from ${SOURCE_REPO}@${TAG} after ${max_attempts} attempts"
      exit 1
    fi
    sleep 5
  done
  if [ ! -f "${dest}" ]; then
    echo "::error::release asset download succeeded but ${dest} was not created"
    exit 1
  fi

  sha256_file "${dest}"
}

DARWIN_ARM64_ASSET="ax-code-darwin-arm64.zip"

DARWIN_ARM64_SHA="$(download_asset "${DARWIN_ARM64_ASSET}")"
download_asset "${DARWIN_ARM64_ASSET}.minisig" >/dev/null
minisign -V \
  -p "${MINISIGN_PUBLIC_KEY}" \
  -m "/tmp/${DARWIN_ARM64_ASSET}" \
  -x "/tmp/${DARWIN_ARM64_ASSET}.minisig"

cat > /tmp/ax-code.rb << HEADER
# typed: false
# frozen_string_literal: true

# Auto-generated by ax-code release tooling — do not edit manually.
#
# node-bundled formula for ax-code. The macOS asset is a node-bundled
# distribution (bin + lib + node_modules), not a single compiled binary, so the
# whole tree installs into libexec and bin/ax-code is a wrapper that runs the
# bundle with the Homebrew node (the launcher needs --experimental-ffi for
# OpenTUI's node:ffi backend and suppresses Node's experimental FFI notice).
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
  url "${RELEASE_BASE}/${DARWIN_ARM64_ASSET}"
  version "${VERSION}"
  sha256 "${DARWIN_ARM64_SHA}"
  license "Apache-2.0"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "node"
  depends_on "ripgrep"

  # The vendored OpenTUI native library is a prebuilt Mach-O with an @rpath
  # install id and zero Mach-O header padding. Homebrew's post-install
  # fix_dynamic_linkage tries to rewrite its dylib id to the long Cellar/opt path
  # and fails ("Updated load commands do not fit in the header"), making the
  # install exit non-zero even though the keg is fine. node:ffi dlopens the
  # library by absolute path at runtime, so its install id is irrelevant. Gzip it
  # during install so the Mach-O linkage scan skips it, then restore it in
  # post_install, which runs after fix_dynamic_linkage.
  OPENTUI_DYLIB = "node_modules/@ax-code/opentui-core/vendor/darwin-arm64/libopentui.dylib"

  def install
    libexec.install Dir["*"]
    (bin/"ax-code").write <<~SH
      #!/bin/sh
      exec "#{formula_opt_bin("node")}/node" --experimental-ffi --disable-warning=ExperimentalWarning "#{libexec}/lib/index-node-tui.js" "\$@"
    SH
    chmod 0755, bin/"ax-code"

    dylib = libexec/OPENTUI_DYLIB
    system "gzip", "-n", "--", dylib if dylib.exist?
  end

  def post_install
    gz = libexec/"#{OPENTUI_DYLIB}.gz"
    return unless gz.exist?

    chmod 0755, gz.dirname
    system "gunzip", "--", gz
  end

  # Homebrew refuses to link any formula while an installed cask shares its
  # token, and upgrade cleanup then removes the previously linked keg — the
  # ax-code command silently vanishes from PATH. The Desktop cask now ships as
  # "ax-code-desktop", but installs of its short-lived "ax-code" token still
  # trigger the skip; give those users the exact recovery commands.
  def caveats
    return unless (HOMEBREW_PREFIX/"Caskroom/ax-code").directory?

    <<~EOS
      The deprecated "ax-code" Desktop cask is installed, so Homebrew skips
      linking this formula and the ax-code command may be missing from PATH.

      Restore the CLI with:
        brew link ax-code
        hash -r

      Then move the Desktop app to its renamed cask:
        brew upgrade --cask ax-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
HEADER

echo "Generated formula:"
cat /tmp/ax-code.rb

try_update_tap() {
  local label="$1"
  local token="$2"
  local repo="$3"
  local formula_path="$4"
  local tap_name="$5"
  local tap_dir
  local status

  tap_dir="$(mktemp -d)"
  echo "Updating ${tap_name} with ${label}"

  # Switch to the tap write token only after all source-repo release assets have
  # been downloaded and hashed.
  export GH_TOKEN="${token}"
  gh auth setup-git || {
    status=$?
    rm -rf "${tap_dir}"
    return "${status}"
  }
  gh repo clone "${repo}" "${tap_dir}" -- --depth 1 || {
    status=$?
    rm -rf "${tap_dir}"
    return "${status}"
  }
  mkdir -p "$(dirname "${tap_dir}/${formula_path}")"
  cp /tmp/ax-code.rb "${tap_dir}/${formula_path}" || {
    status=$?
    rm -rf "${tap_dir}"
    return "${status}"
  }
  (
    cd "${tap_dir}" || exit
    git config user.name "github-actions[bot]" || exit
    git config user.email "github-actions[bot]@users.noreply.github.com" || exit
    git add "${formula_path}" || exit
    if git diff --cached --quiet; then
      echo "Formula unchanged, skipping push"
    else
      git commit -m "Update ax-code to v${VERSION}" || exit
      for attempt in 1 2 3 4 5; do
        git pull --rebase origin main || exit
        if git push origin HEAD:main; then
          echo "${tap_name} updated to v${VERSION}"
          exit 0
        fi
        echo "::warning::${tap_name} changed during publish; retrying (${attempt}/5)"
        sleep $((attempt * 2))
      done
      echo "::error::Could not publish ax-code to ${tap_name} after 5 attempts"
      exit 1
    fi
  )
  status=$?
  rm -rf "${tap_dir}"
  return "${status}"
}

update_tap() {
  local repo="$1"
  local formula_path="$2"
  local tap_name="$3"
  local index
  local last_index

  last_index=$((${#TAP_AUTH_TOKENS[@]} - 1))
  for index in "${!TAP_AUTH_TOKENS[@]}"; do
    if try_update_tap \
      "${TAP_AUTH_LABELS[$index]}" \
      "${TAP_AUTH_TOKENS[$index]}" \
      "${repo}" \
      "${formula_path}" \
      "${tap_name}"; then
      return 0
    fi

    if [ "${index}" -lt "${last_index}" ]; then
      echo "::warning::${tap_name} update failed with ${TAP_AUTH_LABELS[$index]}; trying next configured token"
    fi
  done

  echo "::error::All configured Homebrew tap tokens failed to update ${tap_name}"
  return 1
}

# Publish the canonical shared tap and keep the former product-specific tap
# current during the migration so existing installations continue to upgrade.
update_tap "defai-digital/homebrew-tap" "Formula/ax-code.rb" "shared Homebrew tap"
update_tap "defai-digital/homebrew-ax-code" "ax-code.rb" "legacy AX Code Homebrew tap"
