#!/usr/bin/env bash
# Update the Homebrew tap with the source-distribution formula.
#
# Generates `ax-code-source.rb` alongside the existing `ax-code.rb`
# (compiled binary) so brew users can opt into the source channel via
# `brew install defai-digital/ax-code/ax-code-source`. Per ADR-002 Phase 2
# this is additive — the default `ax-code` formula stays on compiled
# until Phase 3 flips defaults.
#
# Inputs (env):
#   GITHUB_REF_NAME — release tag (e.g. v4.0.16)
#   GH_TOKEN        — write access to the tap repo
#
# The npm source tarball must already be published before this runs;
# fetch its sha256 from the registry rather than rebuilding here so the
# formula always references exactly what was published.
set -euo pipefail

VERSION="${GITHUB_REF_NAME#v}"
TARBALL_URL="https://registry.npmjs.org/@defai.digital/ax-code/-/ax-code-${VERSION}.tgz"

# Wait briefly for the npm registry to converge — publish-source job
# completes before this homebrew-source job runs, but the registry CDN
# can lag a few seconds before the tarball is fetchable.
attempts=0
max_attempts=30
while ! curl -fsSL -o /tmp/ax-code-source.tgz "$TARBALL_URL"; do
  attempts=$((attempts + 1))
  if [ "$attempts" -ge "$max_attempts" ]; then
    echo "::error::source tarball not available at $TARBALL_URL after $max_attempts attempts"
    exit 1
  fi
  sleep 5
done

if command -v sha256sum >/dev/null 2>&1; then
  SHA="$(sha256sum /tmp/ax-code-source.tgz | cut -d' ' -f1)"
else
  SHA="$(shasum -a 256 /tmp/ax-code-source.tgz | cut -d' ' -f1)"
fi

cat > /tmp/ax-code-source.rb << HEADER
# typed: false
# frozen_string_literal: true

# Auto-generated by release workflow — do not edit manually.
#
# Source-distribution variant of ax-code. Ships pre-bundled JavaScript
# plus the bun runtime as a Homebrew dependency. Avoids the
# bun build --compile × Worker bug class that affects the compiled
# binary on some terminals (oven-sh/bun#26762, #27766, #29124).
#
# This is the additive opt-in formula introduced by ADR-002 Phase 2.
# The default \`ax-code\` formula continues to ship the compiled binary
# until ADR-002 Phase 3 flips the default.
class AxCodeSource < Formula
  desc "Sovereign AI coding agent (source distribution)"
  homepage "https://github.com/defai-digital/ax-code"
  url "${TARBALL_URL}"
  sha256 "${SHA}"
  version "${VERSION}"
  license "MIT"

  depends_on "bun"
  depends_on "ripgrep"

  def install
    libexec.install Dir["*"]

    (bin/"ax-code").write <<~EOS
      #!/bin/sh
      AX_CODE_ORIGINAL_CWD="\$(pwd)" exec "#{Formula["bun"].opt_bin}/bun" "#{libexec}/bundle/index.js" "\$@"
    EOS
    (bin/"ax-code").chmod 0755
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
HEADER

echo "Generated ax-code-source.rb:"
cat /tmp/ax-code-source.rb

git clone "https://x-access-token:${GH_TOKEN}@github.com/defai-digital/homebrew-ax-code.git" /tmp/tap
cp /tmp/ax-code-source.rb /tmp/tap/ax-code-source.rb
cd /tmp/tap
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add ax-code-source.rb
if ! git diff --cached --quiet; then
  git commit -m "Update ax-code-source to v${VERSION}"
  git push
  echo "Homebrew tap (source variant) updated to v${VERSION}"
else
  echo "Source formula unchanged, skipping push"
fi
