/**
 * Knowledge Cards-lite: high-density index distilled from openwiki pages.
 */

import path from "path"
import { mkdir, writeFile } from "fs/promises"
import type { WikiPage } from "./pages"
import { loadWikiPages } from "./pages"
import { detectWiki } from "./detect"

export type WikiCard = {
  title: string
  path: string
  summary: string
  symbols: string[]
}

export type WikiCardsResult = {
  root: string
  wikiDirRelative: string
  cards: WikiCard[]
  markdown: string
  /** Default write path under project (.ax-code/wiki-cards.md) */
  defaultOutputPath: string
}

function pageStem(wikiRel: string): string {
  return path.basename(wikiRel).replace(/\.md$/i, "")
}

export function cardsFromPages(pages: WikiPage[]): WikiCard[] {
  // Prefer content pages over pure indexes for card density
  const ranked = [...pages].sort((a, b) => {
    const aIndex = /^(quickstart|index|readme|cards)$/i.test(pageStem(a.wikiRel)) ? 1 : 0
    const bIndex = /^(quickstart|index|readme|cards)$/i.test(pageStem(b.wikiRel)) ? 1 : 0
    if (aIndex !== bIndex) return aIndex - bIndex
    return a.title.localeCompare(b.title)
  })

  return ranked.map((p) => ({
    title: p.title,
    path: p.relPath,
    summary: p.summary,
    symbols: p.symbols,
  }))
}

export function renderCardsMarkdown(input: {
  wikiDirRelative: string
  cards: WikiCard[]
  generatedAt?: string
}): string {
  const when = input.generatedAt ?? new Date().toISOString()
  const lines = [
    "<!--",
    "Generated by: ax-code wiki cards",
    `Source: ${input.wikiDirRelative}/`,
    `Generated at: ${when}`,
    "Refresh: ax-code wiki cards",
    "-->",
    "",
    "# Wiki cards (lite)",
    "",
    "High-density index of the OpenWiki semantic wiki for agents. Prefer reading linked pages for detail.",
    "For precise symbols use `code_intelligence` / `lsp`.",
    "",
  ]

  if (input.cards.length === 0) {
    lines.push("_No wiki pages found._", "")
    return lines.join("\n")
  }

  for (const card of input.cards) {
    lines.push(`## ${card.title}`)
    lines.push("")
    lines.push(`- **Path:** \`${card.path}\``)
    if (card.symbols.length) {
      lines.push(`- **Symbols:** ${card.symbols.map((s) => `\`${s}\``).join(", ")}`)
    }
    if (card.summary) {
      lines.push(`- **Summary:** ${card.summary}`)
    }
    lines.push("")
  }

  return lines.join("\n")
}

export async function buildWikiCards(input: {
  root: string
  dir?: string
}): Promise<WikiCardsResult | { error: string }> {
  const det = await detectWiki({ root: input.root, dir: input.dir })
  if (!det.wikiExists) {
    return { error: `No wiki directory at ${det.wikiDirRelative}/. Run: ax-code wiki generate` }
  }
  const pages = await loadWikiPages({ root: det.root, wikiDir: det.wikiDir })
  const cards = cardsFromPages(pages)
  const markdown = renderCardsMarkdown({
    wikiDirRelative: det.wikiDirRelative,
    cards,
  })
  const defaultOutputPath = path.join(det.root, ".ax-code", "wiki-cards.md")
  return {
    root: det.root,
    wikiDirRelative: det.wikiDirRelative,
    cards,
    markdown,
    defaultOutputPath,
  }
}

export async function writeWikiCards(outputPath: string, markdown: string): Promise<void> {
  await mkdir(path.dirname(outputPath), { recursive: true })
  await writeFile(outputPath, markdown, "utf-8")
}
