/**
 * AGENTS.md instruction generator
 *
 * Generates token-efficient, comprehension-optimized project context.
 * Supports depth levels: basic, standard, full, security
 */

import type { ProjectInfo, DepthLevel, ComplexityLevel } from "./analyzer"

interface GeneratorConfig {
  depth: DepthLevel
  includeTroubleshooting: boolean
  includeCodePatterns: boolean
  externalRules?: string[]
  adaptiveOutput?: boolean
}

const DEFAULT_CONFIG: GeneratorConfig = {
  depth: "standard",
  includeTroubleshooting: true,
  includeCodePatterns: true,
  adaptiveOutput: true,
}

export function generate(info: ProjectInfo, config: Partial<GeneratorConfig> = {}): string {
  const cfg = { ...DEFAULT_CONFIG, ...config }
  const sections: string[] = []
  const depth = effectiveDepth(cfg, info)
  const complexity = info.complexity?.level || "medium"

  sections.push(metadataHeader(info))
  sections.push(projectHeader(info))
  sections.push(buildCommands(info))

  if (depth !== "basic" || complexity !== "small") {
    sections.push(architectureOverview(info))
  }

  sections.push(projectRules(info, cfg.externalRules))

  if (cfg.includeCodePatterns && (depth === "full" || depth === "security" || complexity === "large" || complexity === "enterprise")) {
    sections.push(codePatterns(info))
  }

  const tips = developmentTips(info, complexity)
  if (tips) sections.push(tips)

  if (cfg.includeTroubleshooting && (depth !== "basic" || complexity !== "small")) {
    const ts = troubleshooting(info)
    if (ts) sections.push(ts)
  }

  return sections.filter(Boolean).join("\n\n")
}

function effectiveDepth(cfg: GeneratorConfig, info: ProjectInfo): DepthLevel {
  if (!cfg.adaptiveOutput) return cfg.depth

  const complexity = info.complexity?.level
  if (!complexity) return cfg.depth

  const order: DepthLevel[] = ["basic", "standard", "full", "security"]
  const upgrade: Record<ComplexityLevel, number> = { small: 0, medium: 0, large: 1, enterprise: 2 }

  const idx = order.indexOf(cfg.depth)
  return order[Math.min(idx + upgrade[complexity], order.length - 1)]
}

function metadataHeader(info: ProjectInfo): string {
  const now = new Date().toISOString().split("T")[0]
  const c = info.complexity
  const detail = c ? `\nComplexity: ${c.level} (${c.fileCount} files, ~${c.linesOfCode} LOC)` : ""
  return `<!--
Generated by: ax-code
Last updated: ${now}${detail}
Refresh: Run \`/init\` or \`ax-code init --refresh\` to update
-->`
}

function projectHeader(info: ProjectInfo): string {
  const parts = [`# ${info.name}`]

  const meta = [`**Type:** ${info.projectType}`, `**Language:** ${info.primaryLanguage}`]
  if (info.packageManager) meta.push(`**PM:** ${info.packageManager}`)
  if (info.version) meta.push(`**Version:** ${info.version}`)
  parts.push(meta.join(" | "))

  if (info.techStack.length > 0) {
    parts.push(`\n**Stack:** ${info.techStack.slice(0, 8).join(", ")}`)
  }

  if (info.description) {
    parts.push(`\n${info.description}`)
  }

  return parts.join("\n")
}

function buildCommands(info: ProjectInfo): string {
  const { scripts, packageManager } = info
  const lines = ["## Build & Development"]
  const run = packageManager === "npm" ? "npm run" : (packageManager || "npm run")
  const install = packageManager ? (packageManager === "npm" ? "npm install" : `${packageManager} install`) : "npm install"
  const cmds: string[] = []

  cmds.push(`${install}    # Install dependencies`)
  if (scripts.build) cmds.push(`${run} build   # Build project`)
  if (scripts.test) {
    cmds.push(packageManager === "npm" ? "npm test    # Run tests" : `${run} test    # Run tests`)
  }
  if (scripts.lint) cmds.push(`${run} lint    # Lint code`)
  if (scripts.dev) cmds.push(`${run} dev     # Development mode`)
  if (scripts.typecheck) cmds.push(`${run} typecheck  # Type check`)

  if (cmds.length > 0) {
    lines.push("```bash", ...cmds, "```")
  }

  if (scripts.custom && Object.keys(scripts.custom).length > 0) {
    const entries = Object.entries(scripts.custom).slice(0, 5)
    if (entries.length > 0) {
      lines.push("\n**Additional scripts:**")
      for (const [name, cmd] of entries) {
        lines.push(`- \`${run} ${name}\` - ${cmd}`)
      }
    }
  }

  return lines.join("\n")
}

function architectureOverview(info: ProjectInfo): string {
  const lines = ["## Architecture"]
  const dirs: string[] = []

  if (info.directories.source) dirs.push(`- \`${info.directories.source}/\` - Source code`)
  if (info.directories.tests) dirs.push(`- \`${info.directories.tests}/\` - Tests`)
  if (info.directories.docs) dirs.push(`- \`${info.directories.docs}/\` - Documentation`)
  if (info.directories.config) dirs.push(`- \`${info.directories.config}/\` - Configuration`)
  if (info.directories.dist) dirs.push(`- \`${info.directories.dist}/\` - Build output`)

  if (dirs.length > 0) {
    lines.push("### Key Directories", ...dirs)
  }

  if (info.entryPoint) {
    lines.push(`\n**Entry point:** \`${info.entryPoint}\``)
  }

  const keyFiles = Object.entries(info.keyFiles).slice(0, 5)
  if (keyFiles.length > 0) {
    lines.push("\n### Key Files")
    for (const [file, desc] of keyFiles) {
      lines.push(`- \`${file}\` - ${desc}`)
    }
  }

  return lines.join("\n")
}

function projectRules(info: ProjectInfo, externalRules?: string[]): string {
  const lines = ["## Project-Specific Rules"]
  const rules: string[] = []

  if (info.conventions.importExtension === ".js") {
    rules.push("ESM imports require `.js` extension: `import { x } from './y.js'`")
  }
  if (info.conventions.moduleSystem === "esm") {
    rules.push("Use ES module syntax (`import`/`export`), not CommonJS (`require`)")
  }
  if (info.conventions.validation) {
    rules.push(`Use \`${info.conventions.validation}\` for runtime validation`)
  }
  if (info.conventions.testFramework) {
    rules.push(`Tests use \`${info.conventions.testFramework}\``)
  }
  if (info.conventions.linter) {
    rules.push(`Code is linted with \`${info.conventions.linter}\``)
  }
  if (info.conventions.strict) {
    rules.push("TypeScript strict mode is enabled")
  }
  if (info.packageManager && info.packageManager !== "npm") {
    rules.push(`Use \`${info.packageManager}\` as the package manager (not npm)`)
  }

  if (externalRules && externalRules.length > 0) {
    rules.push(...externalRules)
  }

  if (rules.length > 0) {
    for (const rule of rules) {
      lines.push(`- ${rule}`)
    }
  }

  return lines.join("\n")
}

function codePatterns(info: ProjectInfo): string {
  const lines = ["## Code Patterns"]

  if (info.primaryLanguage === "TypeScript") {
    lines.push("### TypeScript")
    if (info.conventions.moduleSystem === "esm") {
      lines.push("```typescript", 'import { something } from "./module.js"', "```")
    }
    if (info.conventions.validation === "zod") {
      lines.push("```typescript", 'import { z } from "zod"', "const schema = z.object({ name: z.string() })", "```")
    }
  }

  return lines.join("\n")
}

function developmentTips(info: ProjectInfo, complexity: ComplexityLevel): string | undefined {
  const tips = [...info.gotchas]
  const maxTips: Record<ComplexityLevel, number> = { small: 3, medium: 5, large: 7, enterprise: 10 }

  if (tips.length === 0) return undefined

  const lines = ["## Development Tips"]
  for (const tip of tips.slice(0, maxTips[complexity])) {
    lines.push(`- ${tip}`)
  }

  return lines.join("\n")
}

function troubleshooting(info: ProjectInfo): string | undefined {
  const lines = ["## Troubleshooting"]
  const items: string[] = []

  if (info.conventions.moduleSystem === "esm") {
    items.push("**Module not found?** Check `.js` extension in import path")
  }
  if (info.conventions.testFramework) {
    items.push(`**Tests failing?** Run \`${info.packageManager || "npm"} run test\` from the correct directory`)
  }

  if (items.length === 0) return undefined

  for (const item of items) {
    lines.push(`- ${item}`)
  }

  return lines.join("\n")
}
