import { readFileSync } from "node:fs"
import { describe, expect, test } from "vitest"
import fixture from "./minisign-fixture.json"
import { RELEASE_PUBLIC_KEY, verifyMinisign } from "../../src/installation/minisign"

const body = Buffer.from(fixture.body)
describe("Minisign interoperability", () => {
  test.each(["prehashed", "legacy"] as const)("accepts an envelope generated by official minisign: %s", (format) => {
    expect(() => verifyMinisign(body, fixture[format], fixture.publicKey)).not.toThrow()
    expect(() => verifyMinisign(body, fixture[format].replaceAll("\n", "\r\n"), fixture.publicKey)).not.toThrow()
  })
  test("rejects altered bytes, comments, keys, algorithms and encodings", () => {
    expect(() => verifyMinisign(Buffer.from("changed"), fixture.prehashed, fixture.publicKey)).toThrow()
    expect(() =>
      verifyMinisign(
        body,
        fixture.prehashed.replace("trusted comment: AX", "trusted comment: OTHER"),
        fixture.publicKey,
      ),
    ).toThrow()
    expect(() => verifyMinisign(body, fixture.prehashed)).toThrow()
    const lines = fixture.prehashed.trimEnd().split("\n")
    const signature = Buffer.from(lines[1], "base64")
    signature[0] = 0
    lines[1] = signature.toString("base64")
    expect(() => verifyMinisign(body, lines.join("\n"), fixture.publicKey)).toThrow()
    expect(() => verifyMinisign(body, fixture.prehashed + "extra", fixture.publicKey)).toThrow()
    expect(() => verifyMinisign(body, "x".repeat(8193), fixture.publicKey)).toThrow()
  })
  test("pins the documented release key", () => {
    expect(readFileSync(new URL("../../../../docs/release/ax-minisign.pub", import.meta.url), "utf8")).toContain(
      RELEASE_PUBLIC_KEY,
    )
  })
})
