const { createAgent } = await import("./src/sdk/programmatic.ts")
console.log("=== AX-CODE PROGRAMMATIC SDK ===")
const s = Date.now()
const a = await createAgent({ directory: process.cwd() })
console.log("createAgent:", Date.now() - s, "ms")
const s2 = Date.now()
const r = await a.run("What is 2+2? One word.")
console.log("run:", Date.now() - s2, "ms")
console.log("TOTAL:", Date.now() - s, "ms")
console.log("Result:", r.text)
await a.dispose()
process.exit(0)
