/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function diffBuffersJson(oldJson: string, newJson: string): string

export declare function parseAnsiJson(input: string): string

export declare function parseInputJson(input: string): string

export declare function wrappedBufferJson(cols: number, rows: number, text: string): string
