/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Apply patch chunks to file content.
 *
 * Each chunk has `{ old_lines, new_lines, change_context?, is_end_of_file? }`.
 * Uses seek_sequence to find old_lines in the file, replaces with new_lines.
 * Returns JSON: `{ new_content, unified_diff, additions, deletions }`
 */
export declare function applyChunks(filePath: string, fileContent: string, chunksJson: string): string

/**
 * Count additions and deletions.
 * Returns JSON: `{ additions, deletions }`
 */
export declare function diffStats(oldContent: string, newContent: string): string

/**
 * Core edit tool function. Tries 9 replacer strategies in order.
 *
 * Returns JSON: `{ new_content, unified_diff, additions, deletions, strategy }`
 */
export declare function editReplace(content: string, oldString: string, newString: string, replaceAll: boolean): string

/**
 * Levenshtein edit distance.
 * BUG-301: Return f64 to avoid truncating usize on very long strings
 */
export declare function levenshtein(a: string, b: string): number

/**
 * 4-pass fuzzy line matching.
 * Returns the index of the first match, or -1.
 */
export declare function seekSequence(
  lines: Array<string>,
  pattern: Array<string>,
  startIndex: number,
  eof: boolean,
): number

/** Normalized string similarity (0.0 - 1.0). */
export declare function similarity(a: string, b: string): number

/** Generate a unified diff between two strings. */
export declare function unifiedDiff(filePath: string, oldContent: string, newContent: string): string
