/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Test-only export for the unicode differential harness: mirrors the Zig
 * `encodeUnicode` observable output as a flat [width0, char0, width1, char1,
 * ...] array (char = codepoint for simple printable-ASCII cells, 0xFFFFFFFF
 * for pooled/special cells). The `__ax` prefix keeps it out of the overlay's
 * yoga/audio symbol families.
 */
export declare function __axEncodeWidths(text: string, widthMethod: number): Array<number>

export declare function audioClearPlaybackDeviceSelection(engine: number): void

export declare function audioCreateGroup(engine: number, a: number, b: number, c: number): number

export declare function audioEnableTap(engine: number, enabled: number, size: number): number

export declare function audioGetPlaybackDeviceCount(engine: number): number

export declare function audioGetPlaybackDeviceName(engine: number, index: number, out: number, cap: number): number

export declare function audioGetStats(engine: number, out: number): number

export declare function audioIsPlaybackDeviceDefault(engine: number, index: number): boolean

export declare function audioLoad(engine: number, data: number, len: number, options: number): number

export declare function audioMixToBuffer(engine: number, buf: number, frames: number, flags: number): number

export declare function audioPlay(engine: number, sound: number, a: number, b: number): number

export declare function audioReadTap(engine: number, buf: number, frames: number, flags: number, out: number): number

export declare function audioRefreshPlaybackDevices(engine: number): number

export declare function audioSelectPlaybackDevice(engine: number, index: number): number

export declare function audioSetGroupVolume(engine: number, group: number, volume: number): number

export declare function audioSetMasterVolume(engine: number, volume: number): number

export declare function audioSetVoiceGroup(engine: number, voice: number, group: number): number

export declare function audioStart(engine: number, options: number): number

export declare function audioStartMixer(engine: number): number

export declare function audioStop(engine: number): number

export declare function audioStopVoice(engine: number, voice: number): number

export declare function audioUnload(engine: number, sound: number): number

export declare function createAudioEngine(options: number): number

export declare function destroyAudioEngine(engine: number): void

export declare function yogaConfigCreate(): number

export declare function yogaConfigFree(config: number): void

export declare function yogaConfigGetErrata(config: number): number

export declare function yogaConfigGetPointScaleFactor(config: number): number

export declare function yogaConfigGetUseWebDefaults(config: number): boolean

export declare function yogaConfigIsExperimentalFeatureEnabled(config: number, feature: number): boolean

export declare function yogaConfigSetErrata(config: number, errata: number): void

export declare function yogaConfigSetExperimentalFeatureEnabled(config: number, feature: number, enabled: number): void

export declare function yogaConfigSetPointScaleFactor(config: number, factor: number): void

export declare function yogaConfigSetUseWebDefaults(config: number, enabled: number): void

export declare function yogaNodeCalculateLayout(node: number, width: number, height: number, direction: number): void

export declare function yogaNodeCopyStyle(dst: number, src: number): void

export declare function yogaNodeCreate(): number

export declare function yogaNodeCreateForOpenTUI(): number

export declare function yogaNodeCreateWithConfig(config: number): number

export declare function yogaNodeFree(node: number): void

export declare function yogaNodeFreeRecursive(node: number): void

export declare function yogaNodeGetAlwaysFormsContainingBlock(node: number): boolean

export declare function yogaNodeGetChild(node: number, index: number): number

export declare function yogaNodeGetChildCount(node: number): number

export declare function yogaNodeGetComputedLayout(node: number, out: number): void

export declare function yogaNodeGetHasNewLayout(node: number): boolean

export declare function yogaNodeGetParent(node: number): number

export declare function yogaNodeHasMeasureFunc(node: number): boolean

export declare function yogaNodeInsertChild(node: number, child: number, index: number): void

export declare function yogaNodeIsDirty(node: number): boolean

export declare function yogaNodeIsReferenceBaseline(node: number): boolean

export declare function yogaNodeLayoutGetEdge(node: number, kind: number, edge: number): number

export declare function yogaNodeMarkDirty(node: number): void

export declare function yogaNodeRemoveAllChildren(node: number): void

export declare function yogaNodeRemoveChild(node: number, child: number): void

export declare function yogaNodeReset(node: number): void

export declare function yogaNodeSetAlwaysFormsContainingBlock(node: number, value: number): void

export declare function yogaNodeSetDirtiedFunc(node: number, callback: number): void

export declare function yogaNodeSetHasNewLayout(node: number, hasNewLayout: number): void

export declare function yogaNodeSetIsReferenceBaseline(node: number, value: number): void

export declare function yogaNodeSetMeasureFunc(node: number, callback: number): void

export declare function yogaNodeStyleGetBorder(node: number, edge: number): number

export declare function yogaNodeStyleGetEnum(node: number, kind: number): number

export declare function yogaNodeStyleGetFloat(node: number, kind: number): number

export declare function yogaNodeStyleGetValue(node: number, kind: number, edgeOrGutter: number): bigint

export declare function yogaNodeStyleSetBorder(node: number, edge: number, value: number): void

export declare function yogaNodeStyleSetEnum(node: number, kind: number, value: number): void

export declare function yogaNodeStyleSetFloat(node: number, kind: number, value: number): void

export declare function yogaNodeStyleSetValue(node: number, kind: number, edgeOrGutter: number, unit: number, value: number): void

export declare function yogaNodeUnsetDirtiedFunc(node: number): void

export declare function yogaNodeUnsetMeasureFunc(node: number): void

export declare function yogaStoreMeasureResult(width: number, height: number): void
