/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Test-only export for the unicode differential harness: mirrors the Zig
 * `encodeUnicode` observable output as a flat [width0, char0, width1, char1,
 * ...] array (char = codepoint for simple printable-ASCII cells, 0xFFFFFFFF
 * for pooled/special cells). The `__ax` prefix keeps it out of the overlay's
 * yoga/audio symbol families.
 */
export declare function __axEncodeWidths(text: string, widthMethod: number): Array<number>

export declare function attributesGetLinkId(attributes: number): number

export declare function attributesWithLink(baseAttributes: number, linkId: number): number

export declare function audioClearPlaybackDeviceSelection(engine: number): void

export declare function audioCreateGroup(engine: number, a: number, b: number, c: number): number

export declare function audioEnableTap(engine: number, enabled: number, size: number): number

export declare function audioGetPlaybackDeviceCount(engine: number): number

export declare function audioGetPlaybackDeviceName(engine: number, index: number, out: number, cap: number): number

export declare function audioGetStats(engine: number, out: number): number

export declare function audioIsPlaybackDeviceDefault(engine: number, index: number): boolean

export declare function audioLoad(engine: number, data: number, len: number, options: number): number

export declare function audioMixToBuffer(engine: number, buf: number, frames: number, flags: number): number

export declare function audioPlay(engine: number, sound: number, a: number, b: number): number

export declare function audioReadTap(engine: number, buf: number, frames: number, flags: number, out: number): number

export declare function audioRefreshPlaybackDevices(engine: number): number

export declare function audioSelectPlaybackDevice(engine: number, index: number): number

export declare function audioSetGroupVolume(engine: number, group: number, volume: number): number

export declare function audioSetMasterVolume(engine: number, volume: number): number

export declare function audioSetVoiceGroup(engine: number, voice: number, group: number): number

export declare function audioStart(engine: number, options: number): number

export declare function audioStartMixer(engine: number): number

export declare function audioStop(engine: number): number

export declare function audioStopVoice(engine: number, voice: number): number

export declare function audioUnload(engine: number, sound: number): number

export declare function bufferClear(handle: number, bg: number): void

export declare function bufferClearOpacity(handle: number): void

export declare function bufferClearScissorRects(handle: number): void

export declare function bufferColorMatrix(handle: number, matrix: number, cellMask: number, cellMaskCount: number, strength: number, target: number): void

export declare function bufferColorMatrixUniform(handle: number, matrix: number, strength: number, target: number): void

export declare function bufferDrawBox(handle: number, x: number, y: number, width: number, height: number, borderChars: number, packedOptions: number, borderColor: number, backgroundColor: number, titleColor: number, titlePtr: number, titleLen: number, bottomTitlePtr: number, bottomTitleLen: number): void

export declare function bufferDrawChar(handle: number, char: number, x: number, y: number, fg: number, bg: number, attributes: number): void

export declare function bufferDrawGrayscaleBuffer(handle: number, posX: number, posY: number, intensities: number, srcWidth: number, srcHeight: number, fg: number, bg: number): void

export declare function bufferDrawGrayscaleBufferSupersampled(handle: number, posX: number, posY: number, intensities: number, srcWidth: number, srcHeight: number, fg: number, bg: number): void

export declare function bufferDrawGrid(handle: number, borderChars: number, borderFg: number, borderBg: number, columnOffsets: number, columnCount: number, rowOffsets: number, rowCount: number, options: number): void

export declare function bufferDrawPackedBuffer(handle: number, data: number, dataLen: number, posX: number, posY: number, terminalWidthCells: number, terminalHeightCells: number): void

export declare function bufferDrawSuperSampleBuffer(handle: number, x: number, y: number, pixelData: number, len: number, format: number, alignedBytesPerRow: number): void

export declare function bufferDrawText(handle: number, textPtr: number, textLen: number, x: number, y: number, fg: number, bg: number, attributes: number): void

export declare function bufferFillRect(handle: number, x: number, y: number, width: number, height: number, bg: number): void

export declare function bufferGetAttributesPtr(handle: number): number

export declare function bufferGetBgPtr(handle: number): number

export declare function bufferGetCharPtr(handle: number): number

export declare function bufferGetCurrentOpacity(handle: number): number

export declare function bufferGetFgPtr(handle: number): number

export declare function bufferGetId(handle: number, outPtr: number, maxLen: number): number

export declare function bufferGetRealCharSize(handle: number): number

export declare function bufferGetRespectAlpha(handle: number): boolean

export declare function bufferPopOpacity(handle: number): void

export declare function bufferPopScissorRect(handle: number): void

export declare function bufferPushOpacity(handle: number, opacity: number): void

export declare function bufferPushScissorRect(handle: number, x: number, y: number, width: number, height: number): void

export declare function bufferResize(handle: number, width: number, height: number): void

export declare function bufferSetCell(handle: number, x: number, y: number, char: number, fg: number, bg: number, attributes: number): void

export declare function bufferSetCellWithAlphaBlending(handle: number, x: number, y: number, char: number, fg: number, bg: number, attributes: number): void

export declare function bufferSetRespectAlpha(handle: number, respectAlpha: number): void

export declare function bufferWriteResolvedChars(handle: number, outputPtr: number, outputLen: number, addLineBreaks: boolean): number

export declare function createAudioEngine(options: number): number

export declare function createOptimizedBuffer(width: number, height: number, respectAlpha: number, widthMethod: number, idPtr: number, idLen: number): number

export declare function createSyntaxStyle(): number

export declare function createTextBuffer(widthMethod: number): number

export declare function createTextBufferView(tbHandle: number): number

export declare function destroyAudioEngine(engine: number): void

export declare function destroyOptimizedBuffer(handle: number): void

export declare function destroySyntaxStyle(handle: number): void

export declare function destroyTextBuffer(handle: number): void

export declare function destroyTextBufferView(handle: number): void

export declare function drawFrameBuffer(handle: number, destX: number, destY: number, srcHandle: number, sourceX: number, sourceY: number, sourceWidth: number, sourceHeight: number): void

export declare function syntaxStyleGetStyleCount(handle: number): number

export declare function syntaxStyleRegister(handle: number, namePtr: number, nameLen: number, fg: number, bg: number, attributes: number): number

export declare function syntaxStyleResolveByName(handle: number, namePtr: number, nameLen: number): number

export declare function textBufferAddHighlight(handle: number, lineIdx: number, hlPtr: number): void

export declare function textBufferAddHighlightByCharRange(handle: number, hlPtr: number): void

export declare function textBufferAppend(handle: number, dataPtr: number, dataLen: number): void

export declare function textBufferAppendFromMemId(handle: number, id: number): void

export declare function textBufferClear(handle: number): void

export declare function textBufferClearAllHighlights(handle: number): void

export declare function textBufferClearLineHighlights(handle: number, lineIdx: number): void

export declare function textBufferClearMemRegistry(handle: number): void

export declare function textBufferFreeLineHighlights(ptr: number, count: number): void

export declare function textBufferGetByteSize(handle: number): number

export declare function textBufferGetHighlightCount(handle: number): number

export declare function textBufferGetLength(handle: number): number

export declare function textBufferGetLineCount(handle: number): number

export declare function textBufferGetLineHighlightsPtr(handle: number, lineIdx: number, outCount: number): number

export declare function textBufferGetPlainText(handle: number, outPtr: number, maxLen: number): number

export declare function textBufferGetTabWidth(handle: number): number

export declare function textBufferGetTextRange(handle: number, startOffset: number, endOffset: number, outPtr: number, maxLen: number): number

export declare function textBufferGetTextRangeByCoords(handle: number, startRow: number, startCol: number, endRow: number, endCol: number, outPtr: number, maxLen: number): number

export declare function textBufferRegisterMemBuffer(handle: number, dataPtr: number, dataLen: number, owned: boolean): number

export declare function textBufferRemoveHighlightsByRef(handle: number, hlRef: number): void

export declare function textBufferReplaceMemBuffer(handle: number, id: number, dataPtr: number, dataLen: number, owned: boolean): boolean

export declare function textBufferReset(handle: number): void

/**
 * StyledChunk extern-struct layout (64-bit): text_ptr@0, text_len@8,
 * fg_ptr@16, bg_ptr@24, attributes@32 (u32 + 4 pad), link_ptr@40, link_len@48.
 */
export declare function textBufferSetStyledText(handle: number, chunksPtr: number, chunkCount: number): void

export declare function textBufferSetSyntaxStyle(handle: number, styleHandle: number): boolean

export declare function textBufferSetTabWidth(handle: number, width: number): void

export declare function textBufferSetTextFromMem(handle: number, id: number): void

/**
 * ExternalLineInfo extern layout (64-bit): starts_ptr@0, starts_len@8,
 * widths_ptr@16, widths_len@24, sources_ptr@32, sources_len@40,
 * wraps_ptr@48, wraps_len@56, width_cols_max@64.
 */
export declare function textBufferViewGetLineInfoDirect(handle: number, outPtr: number): void

export declare function textBufferViewGetPlainText(handle: number, outPtr: number, maxLen: number): number

export declare function textBufferViewGetSelectedText(handle: number, outPtr: number, maxLen: number): number

export declare function textBufferViewGetSelectionInfo(handle: number): number

export declare function textBufferViewGetVirtualLineCount(handle: number): number

export declare function textBufferViewResetLocalSelection(handle: number): void

export declare function textBufferViewResetSelection(handle: number): void

export declare function textBufferViewSetFirstLineOffset(handle: number, offset: number): void

export declare function textBufferViewSetLocalSelection(handle: number, ax: number, ay: number, fx: number, fy: number, bg: number, fg: number): boolean

export declare function textBufferViewSetSelection(handle: number, start: number, end: number, bg: number, fg: number): void

export declare function textBufferViewSetViewport(handle: number, x: number, y: number, width: number, height: number): void

export declare function textBufferViewSetViewportSize(handle: number, width: number, height: number): void

export declare function textBufferViewSetWrapMode(handle: number, mode: number): void

export declare function textBufferViewSetWrapWidth(handle: number, width: number): void

export declare function textBufferViewUpdateLocalSelection(handle: number, ax: number, ay: number, fx: number, fy: number, bg: number, fg: number): boolean

export declare function textBufferViewUpdateSelection(handle: number, end: number, bg: number, fg: number): void

export declare function yogaConfigCreate(): number

export declare function yogaConfigFree(config: number): void

export declare function yogaConfigGetErrata(config: number): number

export declare function yogaConfigGetPointScaleFactor(config: number): number

export declare function yogaConfigGetUseWebDefaults(config: number): boolean

export declare function yogaConfigIsExperimentalFeatureEnabled(config: number, feature: number): boolean

export declare function yogaConfigSetErrata(config: number, errata: number): void

export declare function yogaConfigSetExperimentalFeatureEnabled(config: number, feature: number, enabled: number): void

export declare function yogaConfigSetPointScaleFactor(config: number, factor: number): void

export declare function yogaConfigSetUseWebDefaults(config: number, enabled: number): void

export declare function yogaNodeCalculateLayout(node: number, width: number, height: number, direction: number): void

export declare function yogaNodeCopyStyle(dst: number, src: number): void

export declare function yogaNodeCreate(): number

export declare function yogaNodeCreateForOpenTUI(): number

export declare function yogaNodeCreateWithConfig(config: number): number

export declare function yogaNodeFree(node: number): void

export declare function yogaNodeFreeRecursive(node: number): void

export declare function yogaNodeGetAlwaysFormsContainingBlock(node: number): boolean

export declare function yogaNodeGetChild(node: number, index: number): number

export declare function yogaNodeGetChildCount(node: number): number

export declare function yogaNodeGetComputedLayout(node: number, out: number): void

export declare function yogaNodeGetHasNewLayout(node: number): boolean

export declare function yogaNodeGetParent(node: number): number

export declare function yogaNodeHasMeasureFunc(node: number): boolean

export declare function yogaNodeInsertChild(node: number, child: number, index: number): void

export declare function yogaNodeIsDirty(node: number): boolean

export declare function yogaNodeIsReferenceBaseline(node: number): boolean

export declare function yogaNodeLayoutGetEdge(node: number, kind: number, edge: number): number

export declare function yogaNodeMarkDirty(node: number): void

export declare function yogaNodeRemoveAllChildren(node: number): void

export declare function yogaNodeRemoveChild(node: number, child: number): void

export declare function yogaNodeReset(node: number): void

export declare function yogaNodeSetAlwaysFormsContainingBlock(node: number, value: number): void

export declare function yogaNodeSetDirtiedFunc(node: number, callback: number): void

export declare function yogaNodeSetHasNewLayout(node: number, hasNewLayout: number): void

export declare function yogaNodeSetIsReferenceBaseline(node: number, value: number): void

export declare function yogaNodeSetMeasureFunc(node: number, callback: number): void

export declare function yogaNodeStyleGetBorder(node: number, edge: number): number

export declare function yogaNodeStyleGetEnum(node: number, kind: number): number

export declare function yogaNodeStyleGetFloat(node: number, kind: number): number

export declare function yogaNodeStyleGetValue(node: number, kind: number, edgeOrGutter: number): bigint

export declare function yogaNodeStyleSetBorder(node: number, edge: number, value: number): void

export declare function yogaNodeStyleSetEnum(node: number, kind: number, value: number): void

export declare function yogaNodeStyleSetFloat(node: number, kind: number, value: number): void

export declare function yogaNodeStyleSetValue(node: number, kind: number, edgeOrGutter: number, unit: number, value: number): void

export declare function yogaNodeUnsetDirtiedFunc(node: number): void

export declare function yogaNodeUnsetMeasureFunc(node: number): void

export declare function yogaStoreMeasureResult(width: number, height: number): void
