/**
 * Memory Recorder
 *
 * API for adding user preferences, feedback rules, and project decisions to
 * project memory. These are user-curated and persist across sessions, in
 * contrast to scanned sections (structure/readme/config/patterns) which are
 * regenerated by the warmup pipeline.
 *
 * Entries are deduped by `name` within each kind — re-recording the same name
 * overwrites the prior entry rather than appending duplicates.
 */

import os from "os"
import * as store from "./store"
import { generate } from "./generator"
import { computeContentHash, renderEntry } from "./hash"
import type { EntrySection, MemoryEntry, MemoryEntryKind, ProjectMemory } from "./types"
import { Log } from "../util/log"

const log = Log.create({ service: "memory.recorder" })

// Serialize concurrent recordEntry / removeEntry calls for the same memory
// file. Two parallel callers would otherwise both `loadOrInit` the same
// snapshot, each apply their mutation, and the second `save` would overwrite
// the first — a classic lost-update race. Cross-process safety is handled by
// `store.save` (atomic tmp+rename); this in-process queue is the missing
// layer for concurrent in-process callers (TUI sessions, parallel agent
// turns, etc.). Each key (project root or "global") gets its own promise
// chain; the entry is dropped once its tail resolves so the Map stays
// bounded by the number of currently in-flight write paths.
const writeQueues = new Map<string, Promise<unknown>>()

async function withWriteQueue<T>(key: string, fn: () => Promise<T>): Promise<T> {
  const prev = writeQueues.get(key) ?? Promise.resolve()
  // Recover from a prior write failure but log it. `then(fn, fn)` would
  // silently swallow the rejection, so an earlier disk error (full disk,
  // permission denied, etc.) was never surfaced to operators — only the
  // mutation it carried was lost. The log gives a forensic trail without
  // breaking the chain (subsequent writes still proceed).
  const next = prev.then(fn, (error) => {
    log.warn("prior memory write failed; proceeding with next write", {
      command: "memory.write_queue",
      status: "error",
      key,
      error,
    })
    return fn()
  })
  writeQueues.set(key, next)
  try {
    return await next
  } finally {
    if (writeQueues.get(key) === next) writeQueues.delete(key)
  }
}

const GLOBAL_KEY = "__global__"

function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4)
}

function rebuildSection(entries: MemoryEntry[]): EntrySection {
  const content = entries.map(renderEntry).join("\n")
  return { entries, tokens: estimateTokens(content) }
}

function recomputeMetrics(memory: ProjectMemory): void {
  memory.totalTokens = Object.values(memory.sections).reduce((sum, s) => sum + (s?.tokens ?? 0), 0)
  // Canonical hash via the shared helper so this matches generator.generate().
  memory.contentHash = computeContentHash(memory)
  memory.updated = new Date().toISOString()
}

async function loadOrInit(projectRoot: string): Promise<ProjectMemory> {
  // Let corrupt-JSON errors propagate so we don't overwrite a recoverable
  // file. `store.load` returns null only for ENOENT (no file yet), in which
  // case it's safe to scaffold from generate().
  const existing = await store.load(projectRoot)
  if (existing) return existing
  return generate(projectRoot)
}

function globalMemoryScaffold(): ProjectMemory {
  const now = new Date().toISOString()
  return {
    version: 1,
    created: now,
    updated: now,
    projectRoot: os.homedir(),
    contentHash: "",
    maxTokens: 2000,
    sections: {},
    totalTokens: 0,
  }
}

async function loadOrInitGlobal(): Promise<ProjectMemory> {
  const existing = await store.loadGlobal()
  if (existing) return existing
  return globalMemoryScaffold()
}

export interface RecordInput {
  name: string
  body: string
  why?: string
  howToApply?: string
  /** Restrict this entry to a subset of agents (empty/undefined = all agents). */
  agents?: string[]
  /**
   * Where to store the entry. "project" (default) saves to .ax-code/memory.json
   * in the project root. "global" saves to ~/.ax-code/memory.json and persists
   * across all projects — intended for user-level preferences and feedback.
   */
  scope?: "project" | "global"
}

/**
 * Add or replace an entry within the given kind. Returns the persisted memory.
 *
 * Serialized per memory file via `withWriteQueue` so two concurrent record
 * calls for the same project (or both global) don't race on
 * load → modify → save and lose one writer's entry.
 */
export async function recordEntry(
  projectRoot: string,
  kind: MemoryEntryKind,
  input: RecordInput,
): Promise<ProjectMemory> {
  const name = input.name.trim()
  if (!name) throw new Error("memory recorder: entry name must be non-empty")
  const body = input.body.trim()
  if (!body) throw new Error("memory recorder: entry body must be non-empty")

  const isGlobal = input.scope === "global"
  const queueKey = isGlobal ? GLOBAL_KEY : projectRoot
  return withWriteQueue(queueKey, async () => {
    const memory = isGlobal ? await loadOrInitGlobal() : await loadOrInit(projectRoot)
    const existing = memory.sections[kind]?.entries ?? []
    const filtered = existing.filter((e) => e.name !== name)
    const agents = input.agents?.map((a) => a.trim()).filter(Boolean)
    const entry: MemoryEntry = {
      name,
      body,
      savedAt: new Date().toISOString(),
      ...(input.why ? { why: input.why.trim() } : {}),
      ...(input.howToApply ? { howToApply: input.howToApply.trim() } : {}),
      ...(agents && agents.length > 0 ? { agents } : {}),
    }
    filtered.push(entry)
    memory.sections[kind] = rebuildSection(filtered)
    recomputeMetrics(memory)

    if (isGlobal) await store.saveGlobal(memory)
    else await store.save(projectRoot, memory)
    return memory
  })
}

/**
 * Remove an entry by name. Returns true if removed, false if not found.
 *
 * Shares the per-file write queue with `recordEntry` so a remove can't
 * interleave with a record on the same file.
 */
export async function removeEntry(
  projectRoot: string,
  kind: MemoryEntryKind,
  name: string,
  scope: "project" | "global" = "project",
): Promise<boolean> {
  const isGlobal = scope === "global"
  const queueKey = isGlobal ? GLOBAL_KEY : projectRoot
  return withWriteQueue(queueKey, async () => {
    const memory = isGlobal
      ? await store.loadGlobal().catch(() => null)
      : await store.load(projectRoot).catch(() => null)
    if (!memory) return false
    const section = memory.sections[kind]
    if (!section) return false
    const before = section.entries.length
    const filtered = section.entries.filter((e) => e.name !== name)
    if (filtered.length === before) return false
    if (filtered.length === 0) memory.sections[kind] = undefined
    else memory.sections[kind] = rebuildSection(filtered)
    recomputeMetrics(memory)
    if (isGlobal) await store.saveGlobal(memory)
    else await store.save(projectRoot, memory)
    return true
  })
}

/**
 * List entries for a given kind, or all entry kinds if omitted.
 */
export async function listEntries(
  projectRoot: string,
  kind?: MemoryEntryKind,
  scope: "project" | "global" = "project",
): Promise<MemoryEntry[]> {
  const isGlobal = scope === "global"
  const memory = isGlobal ? await store.loadGlobal().catch(() => null) : await store.load(projectRoot).catch(() => null)
  if (!memory) return []
  if (kind) return memory.sections[kind]?.entries ?? []
  const kinds: MemoryEntryKind[] = ["userPrefs", "feedback", "decisions", "reference"]
  return kinds.flatMap((k) => memory.sections[k]?.entries ?? [])
}
