/**
 * Memory Recorder
 *
 * API for adding user preferences, feedback rules, and project decisions to
 * project memory. These are user-curated and persist across sessions, in
 * contrast to scanned sections (structure/readme/config/patterns) which are
 * regenerated by the warmup pipeline.
 *
 * Entries are deduped by `name` within each kind — re-recording the same name
 * overwrites the prior entry rather than appending duplicates.
 */

import crypto from "crypto"
import * as store from "./store"
import { generate } from "./generator"
import type { EntrySection, MemoryEntry, MemoryEntryKind, ProjectMemory } from "./types"

function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4)
}

function renderEntry(entry: MemoryEntry): string {
  const parts = [`- ${entry.name}: ${entry.body}`]
  if (entry.why) parts.push(`  - Why: ${entry.why}`)
  if (entry.howToApply) parts.push(`  - Apply: ${entry.howToApply}`)
  return parts.join("\n")
}

function rebuildSection(entries: MemoryEntry[]): EntrySection {
  const content = entries.map(renderEntry).join("\n")
  return { entries, tokens: estimateTokens(content) }
}

function recomputeMetrics(memory: ProjectMemory): void {
  const allContent: string[] = []
  for (const section of Object.values(memory.sections)) {
    if (!section) continue
    if ("content" in section) allContent.push(section.content)
    else allContent.push(section.entries.map(renderEntry).join("\n"))
  }
  const joined = allContent.join("\n")
  memory.contentHash = crypto.createHash("sha256").update(joined).digest("hex").slice(0, 16)
  memory.totalTokens = Object.values(memory.sections).reduce((sum, s) => sum + (s?.tokens ?? 0), 0)
  memory.updated = new Date().toISOString()
}

async function loadOrInit(projectRoot: string): Promise<ProjectMemory> {
  // Let corrupt-JSON errors propagate so we don't overwrite a recoverable
  // file. `store.load` returns null only for ENOENT (no file yet), in which
  // case it's safe to scaffold from generate().
  const existing = await store.load(projectRoot)
  if (existing) return existing
  return generate(projectRoot)
}

export interface RecordInput {
  name: string
  body: string
  why?: string
  howToApply?: string
  /** Restrict this entry to a subset of agents (empty/undefined = all agents). */
  agents?: string[]
}

/**
 * Add or replace an entry within the given kind. Returns the persisted memory.
 */
export async function recordEntry(
  projectRoot: string,
  kind: MemoryEntryKind,
  input: RecordInput,
): Promise<ProjectMemory> {
  const name = input.name.trim()
  if (!name) throw new Error("memory recorder: entry name must be non-empty")
  const body = input.body.trim()
  if (!body) throw new Error("memory recorder: entry body must be non-empty")

  const memory = await loadOrInit(projectRoot)
  const existing = memory.sections[kind]?.entries ?? []
  const filtered = existing.filter((e) => e.name !== name)
  const agents = input.agents?.map((a) => a.trim()).filter(Boolean)
  const entry: MemoryEntry = {
    name,
    body,
    savedAt: new Date().toISOString(),
    ...(input.why ? { why: input.why.trim() } : {}),
    ...(input.howToApply ? { howToApply: input.howToApply.trim() } : {}),
    ...(agents && agents.length > 0 ? { agents } : {}),
  }
  filtered.push(entry)
  memory.sections[kind] = rebuildSection(filtered)
  recomputeMetrics(memory)

  await store.save(projectRoot, memory)
  return memory
}

/**
 * Remove an entry by name. Returns true if removed, false if not found.
 */
export async function removeEntry(projectRoot: string, kind: MemoryEntryKind, name: string): Promise<boolean> {
  const memory = await store.load(projectRoot).catch(() => null)
  if (!memory) return false
  const section = memory.sections[kind]
  if (!section) return false
  const before = section.entries.length
  const filtered = section.entries.filter((e) => e.name !== name)
  if (filtered.length === before) return false
  if (filtered.length === 0) memory.sections[kind] = undefined
  else memory.sections[kind] = rebuildSection(filtered)
  recomputeMetrics(memory)
  await store.save(projectRoot, memory)
  return true
}

/**
 * List entries for a given kind, or all entry kinds if omitted.
 */
export async function listEntries(projectRoot: string, kind?: MemoryEntryKind): Promise<MemoryEntry[]> {
  const memory = await store.load(projectRoot).catch(() => null)
  if (!memory) return []
  if (kind) return memory.sections[kind]?.entries ?? []
  const kinds: MemoryEntryKind[] = ["userPrefs", "feedback", "decisions"]
  return kinds.flatMap((k) => memory.sections[k]?.entries ?? [])
}
