/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Persistent file tree with cached mtime-sorted index.
 * Reuse across multiple glob/search calls to avoid re-walking.
 */
export declare class FileTree {
  constructor(root: string)
  /** Full scan of the directory tree. Returns { files, dirs, elapsedMs }. */
  scan(): string
  /** Glob query against cached file tree (no disk I/O after scan). */
  glob(pattern: string, limit: number): string
  /** Number of files in the tree. */
  fileCount(): number
  /** Update a single file entry (called from watcher callback). */
  updateFile(relPath: string, absPath: string): void
  /** Remove a file entry (called from watcher callback). */
  removeFile(relPath: string): void
  /** Check if a file exists in the cached tree. */
  hasFile(relPath: string): boolean
  /** Get file metadata from cache. */
  fileMeta(relPath: string): string | null
}

/**
 * Native filesystem watcher using fsevents (macOS) or inotify (Linux).
 * Replaces the 100ms polling loop in TypeScript.
 *
 * Usage from TypeScript:
 *   const watcher = new NativeWatcher(root, ignorePatternsJson)
 *   watcher.poll() // returns JSON array of events since last poll
 *   watcher.stop()
 */
export declare class NativeWatcher {
  constructor(root: string, ignorePatternsJson: string)
  /**
   * Poll for events since last call. Returns JSON array of events.
   * Non-blocking — returns empty array if no events pending.
   */
  poll(): string
  /** Stop watching. Releases OS resources. */
  stop(): void
  /** Check if the watcher is still active. */
  get isActive(): boolean
}

/**
 * Split a file into chunks suitable for embedding.
 * Chunks at paragraph/function boundaries when possible, otherwise at line count.
 */
export declare function chunkFile(path: string, content: string, maxLines: number, overlapLines: number): string

/** Compute content hash for dedup. */
export declare function contentHash(content: string): string

export declare function detectHardcodes(inputJson: string): string

export declare function detectLifecycle(inputJson: string): string

export declare function detectSecurity(inputJson: string): string

/** Estimate token count for a string (rough: ~4 chars per token). */
export declare function estimateTokens(content: string): number

export declare function globFiles(cwd: string, pattern: string, limit: number): string

export declare function isIgnored(path: string, extraPatternsJson: string): boolean

/** Normalize text for embedding: collapse whitespace, strip comments, normalize unicode. */
export declare function normalizeForEmbedding(content: string): string

/**
 * Batch file reader: reads multiple files in parallel using rayon.
 * Returns a JSON object mapping file paths to their UTF-8 contents.
 * Files that fail to read (binary, permissions, etc.) are silently skipped.
 */
export declare function readFilesBatch(filesJson: string): string

/**
 * Batch file scanner: walks once, reads each file once, runs all regex
 * patterns in parallel using rayon. Returns all matches grouped by file.
 */
export declare function scanFiles(cwd: string, configJson: string): string

export declare function searchContent(cwd: string, pattern: string, optionsJson: string): string

export declare function walkFiles(cwd: string, optionsJson: string): Array<string>
