/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Advisory file lock using flock() on Unix.
 * Auto-releases on process crash (kernel-level).
 */
export declare class AdvisoryLock {
  constructor(lockPath: string)
  /** Non-blocking lock attempt. Returns true if acquired. */
  tryAcquire(): boolean
  /** Blocking lock with timeout. Returns true if acquired within timeout. */
  acquire(timeoutMs: number): boolean
  /** Release the lock */
  release(): void
  get isAcquired(): boolean
}

/**
 * `Option<Connection>` rather than bare `Connection` so `close` can take the
 * connection out and run `Connection::close` (which consumes self, runs the
 * final WAL checkpoint, and surfaces close-time errors). After close every
 * further `with_conn*` call returns "store is closed" instead of silently
 * reopening, which would defeat the point of the shutdown release.
 */
export declare class IndexStore {
  getCursor(projectId: string): string | null
  upsertCursor(projectId: string, commitSha: string | undefined | null, nodeCount: number, edgeCount: number): void
  /** Clear all data for a project */
  clearProject(projectId: string): void
  /** Run ANALYZE on graph tables to refresh query planner statistics */
  analyze(): void
  insertEdges(json: string): void
  edgesFrom(projectId: string, fromNode: string, kind?: string | undefined | null): string
  edgesTo(projectId: string, toNode: string, kind?: string | undefined | null): string
  edgesInFile(projectId: string, file: string): string
  deleteEdgesInFile(projectId: string, file: string): void
  deleteEdgesTouchingFile(projectId: string, file: string): void
  countEdges(projectId: string): number
  upsertFile(json: string): void
  getFile(projectId: string, path: string): string | null
  listFiles(projectId: string): string
  deleteFile(projectId: string, path: string): void
  /** Prune files (and their nodes/edges) that are NOT in the live set. */
  pruneOrphanFiles(projectId: string, livePathsJson: string, scopePrefix: string): string
  /** Atomic ingest: delete old data for a file and insert new nodes/edges/file metadata. */
  ingestFile(projectId: string, filePath: string, nodesJson: string, edgesJson: string, fileMetaJson: string): void
  insertNodes(json: string): void
  getNode(projectId: string, id: string): string | null
  findNodesByName(projectId: string, name: string, optsJson: string): string
  findNodesByPrefix(projectId: string, prefix: string, optsJson: string): string
  nodesInFile(projectId: string, file: string): string
  countNodes(projectId: string): number
  deleteNodesInFile(projectId: string, file: string): void
  recentNodes(projectId: string, limit: number): string
  constructor(dbPath: string)
  /**
   * Explicitly release the underlying SQLite connection. Truncates the WAL
   * before closing so external readers see a fully-checkpointed main DB,
   * then consumes the connection via `Connection::close` to run SQLite's
   * own clean-shutdown path. Idempotent — calling close on an already-
   * closed store is a no-op.
   *
   * Once closed, every other method on this store returns
   * "index store is closed" (see `with_conn` / `with_conn_mut`). Callers
   * must drop their JS handle and re-construct an `IndexStore` if they
   * need to resume work; the singleton in `native-store.ts` enforces this
   * by clearing its cached instance on close.
   */
  close(): void
}

/**
 * O(log n) interval tree for finding the innermost containing node.
 *
 * This is an augmented sorted-intervals approach:
 * intervals are sorted by start position, and we binary search
 * to find candidates, then select the smallest (innermost) container.
 */
export declare class IntervalTree {
  constructor()
  insert(
    startLine: number,
    startChar: number,
    endLine: number,
    endChar: number,
    nodeId: string,
    kind: string,
    name: string,
  ): void
  /**
   * Find the innermost named container node at the given position.
   * Returns the node_id of the smallest container, or None.
   */
  findInnermostContainer(line: number, char: number): string | null
  /**
   * Find the innermost container of any kind (including non-container kinds).
   * Used for lookup_caller_kind.
   */
  findInnermostNode(line: number, char: number): string | null
  /** Get the kind of a node by ID */
  getNodeKind(nodeId: string): string | null
  clear(): void
  len(): number
  isEmpty(): boolean
}

export declare function generateId(prefix: string): string

export declare function hashFileSha256(path: string): string

export declare function hashSha256(data: Buffer): string
