import { describe, expect, test } from "bun:test"
import { createFixtureCommandCenterState } from "../../src/projection/replay"
import { createCommandCenterViewModel } from "../../src/projection/view-model"

describe("renderer smoke contract", () => {
  test("fixture first screen exposes command-center essentials", () => {
    const view = createCommandCenterViewModel(createFixtureCommandCenterState())

    expect(view.sessions.length).toBeGreaterThan(0)
    expect(view.queueSummary.total).toBeGreaterThan(0)
    expect(view.queueSummary.running).toBe(1)
    expect(view.goal?.objective).toContain("command center")
    expect(view.permissions.length + view.questions.length).toBeGreaterThan(0)
    expect(view.evidence?.risk?.level).toBe("MEDIUM")
    expect(view.evidence?.artifactCounts.verificationEnvelopes).toBe(2)
    expect(view.catalog.agents.length).toBeGreaterThan(0)
    expect(view.catalog.skills.length).toBeGreaterThan(0)
    expect(view.catalog.models.length).toBeGreaterThan(0)
    expect(view.catalog.lsp.connected).toBeGreaterThan(0)
    expect(view.catalog.codeIndex.nodeCount).toBeGreaterThan(0)
    expect(view.worktrees.length).toBeGreaterThan(0)
    expect(view.terminals.length).toBeGreaterThan(0)
    expect(view.scheduledTasks.length).toBeGreaterThan(0)
  })

  test("app shell keeps basic accessibility landmarks", async () => {
    const source = await Bun.file(new URL("../../src/App.tsx", import.meta.url)).text()

    expect(source).toContain('class="skip-link"')
    expect(source).toContain('role="status"')
    expect(source).toContain('aria-live="polite"')
    expect(source).toContain("aria-current")
    expect(source).toContain("New session")
    expect(source).toContain("createSessionAction")
    expect(source).toContain("onMenuCommand")
    expect(source).toContain("composer.focus")
    expect(source).toContain("chooseAndStartProjectDirectory")
    expect(source).toContain("Open project")
    expect(source).toContain("attachToBackendUrl")
    expect(source).toContain("Attach backend")
    expect(source).toContain("Attach backend authorization header")
    expect(source).toContain("Remote backend mode")
    expect(source).toContain("Backend network mode")
    expect(source).toContain("queueBrowserVerificationTask")
    expect(source).toContain("Open preview")
    expect(source).toContain("Browser previews")
    expect(source).toContain("Close browser preview")
    expect(source).toContain("Verify")
    expect(source).toContain("terminalScopeLabel")
    expect(source).toContain('role="tab"')
    expect(source).toContain('role="tabpanel"')
    expect(source).toContain('aria-labelledby="tool-tab-terminal"')
    expect(source).toContain("Open editor")
    expect(source).toContain("Always")
    expect(source).toContain("Auto-accept allowed permissions")
    expect(source).toContain("Branch rank")
    expect(source).toContain("Submit answer")
    expect(source).toContain("Custom answer")
    expect(source).toContain('role="group" aria-label="Composer mode"')
    expect(source).toContain("aria-pressed")
    expect(source).toContain('class="reconnect-banner"')
    expect(source).toContain('aria-label="Event stream status"')
    expect(source).toContain("Reconnecting to backend events")
    expect(source).toContain("<DiagnosticsPanel")
    expect(source).toContain("openDownloadedUpdate")
    expect(source).toContain("Project defaults")
    expect(source).toContain("Backend reload required")
    expect(source).toContain("Runtime probes")
    expect(source).toContain("Refresh probes")
    expect(source).toContain("Skills")
    expect(source).toContain("skillSummaryLabel")
    expect(source).toContain("<ComposerAttachments")

    const attachmentSource = await Bun.file(new URL("../../src/ComposerAttachments.tsx", import.meta.url)).text()
    expect(attachmentSource).toContain('aria-label="Composer attachments"')
    expect(attachmentSource).toContain('aria-label="Attachment path"')
    expect(attachmentSource).toContain('aria-label="Attached context"')

    const styles = await Bun.file(new URL("../../src/styles/app.css", import.meta.url)).text()
    expect(styles).toContain(":focus-visible")
    expect(styles).toContain("outline")
  })
})
