import type { Translate } from "../i18n"
import type { CommandOption } from "./dialog-command"
import type { OverlayStyle } from "./foliage-view-model"

const PREVIEWS = [
  {
    family: "Digital Code",
    ending: false,
    style: "digital-code",
    key: "animation.digitalOpening",
    value: "app.digital_code.original",
    slash: "digital-code",
  },
  {
    family: "Digital Code",
    ending: true,
    style: "digital-code",
    key: "animation.digitalEnding",
    value: "app.digital_code.original_reverse",
    slash: "digital-code-ending",
  },
  {
    family: "Foliage",
    ending: false,
    style: "classic-foliage",
    key: "animation.classicFoliage",
    value: "app.animation.foliage",
    slash: "foliage",
  },
  {
    family: "Foliage",
    ending: true,
    style: "golden-foliage",
    key: "animation.goldenFoliage",
    value: "app.animation.foliage_ending",
    slash: "foliage-ending",
  },
  {
    family: "Bench",
    ending: false,
    style: "midnight-dream",
    key: "animation.midnightDream",
    value: "app.animation.bench",
    slash: "bench",
  },
  {
    family: "Bench",
    ending: true,
    style: "sunset-serenade",
    key: "animation.sunsetSerenade",
    value: "app.animation.bench_ending",
    slash: "bench-ending",
  },
  {
    family: "Fuji Mountain",
    ending: false,
    style: "fuji-day",
    key: "animation.fujiDay",
    value: "app.animation.fuji",
    slash: "fuji",
  },
  {
    family: "Fuji Mountain",
    ending: true,
    style: "fuji-night",
    key: "animation.fujiNight",
    value: "app.animation.fuji_ending",
    slash: "fuji-ending",
  },
  {
    family: "Mahjong",
    ending: false,
    style: "mahjong-match",
    key: "animation.mahjongMatch",
    value: "app.animation.mahjong",
    slash: "mahjong",
  },
  {
    family: "Mahjong",
    ending: true,
    style: "mahjong-ending",
    key: "animation.mahjongEnding",
    value: "app.animation.mahjong_ending",
    slash: "mahjong-ending",
  },
  {
    family: "City",
    ending: false,
    style: "city-night",
    key: "animation.cityNight",
    value: "app.animation.city",
    slash: "city",
  },
  {
    family: "City",
    ending: true,
    style: "city-dawn",
    key: "animation.cityDawn",
    value: "app.animation.city_ending",
    slash: "city-ending",
  },
  {
    family: "Festival",
    ending: false,
    style: "festival-fireworks",
    key: "animation.festivalFireworks",
    value: "app.animation.festival",
    slash: "festival",
  },
  {
    family: "Festival",
    ending: true,
    style: "festival-lanterns",
    key: "animation.festivalLanterns",
    value: "app.animation.festival_ending",
    slash: "festival-ending",
  },
  {
    family: "Snow",
    ending: false,
    style: "snowfall",
    key: "animation.snowfall",
    value: "app.animation.snow",
    slash: "snow",
  },
  {
    family: "Snow",
    ending: true,
    style: "winter-night",
    key: "animation.winterNight",
    value: "app.animation.snow_ending",
    slash: "snow-ending",
  },
  {
    family: "Volcano",
    ending: false,
    style: "volcano-eruption",
    key: "animation.volcanoEruption",
    value: "app.animation.volcano",
    slash: "volcano",
  },
  {
    family: "Volcano",
    ending: true,
    style: "volcano-calm",
    key: "animation.volcanoCalm",
    value: "app.animation.volcano_ending",
    slash: "volcano-ending",
  },
  {
    family: "Big Ben",
    ending: false,
    style: "bigben-day",
    key: "animation.bigbenDay",
    value: "app.animation.bigben",
    slash: "bigben",
  },
  {
    family: "Big Ben",
    ending: true,
    style: "bigben-night",
    key: "animation.bigbenNight",
    value: "app.animation.bigben_ending",
    slash: "bigben-ending",
  },
  {
    family: "Taipei 101",
    ending: false,
    style: "taipei101-day",
    key: "animation.taipei101Day",
    value: "app.animation.taipei101",
    slash: "taipei101",
  },
  {
    family: "Taipei 101",
    ending: true,
    style: "taipei101-neon",
    key: "animation.taipei101Neon",
    value: "app.animation.taipei101_ending",
    slash: "taipei101-ending",
  },
  {
    family: "Great Wall",
    ending: false,
    style: "greatwall-dawn",
    key: "animation.greatWallDawn",
    value: "app.animation.greatwall",
    slash: "greatwall",
  },
  {
    family: "Great Wall",
    ending: true,
    style: "greatwall-dusk",
    key: "animation.greatWallDusk",
    value: "app.animation.greatwall_ending",
    slash: "greatwall-ending",
  },
  {
    family: "Torii Gate",
    ending: false,
    style: "torii-day",
    key: "animation.toriiDay",
    value: "app.animation.torii",
    slash: "torii",
  },
  {
    family: "Torii Gate",
    ending: true,
    style: "torii-night",
    key: "animation.toriiNight",
    value: "app.animation.torii_ending",
    slash: "torii-ending",
  },
  {
    family: "Taegeuk",
    ending: false,
    style: "taegeuk",
    key: "animation.taegeukSpin",
    value: "app.animation.taegeuk",
    slash: "taegeuk",
  },
  {
    family: "Taegeuk",
    ending: true,
    style: "taegeuk",
    key: "animation.taegeukReverse",
    value: "app.animation.taegeuk_ending",
    slash: "taegeuk-ending",
  },
  {
    family: "Sagrada Familia",
    ending: false,
    style: "sagrada-day",
    key: "animation.sagradaDay",
    value: "app.animation.sagrada",
    slash: "sagrada",
  },
  {
    family: "Sagrada Familia",
    ending: true,
    style: "sagrada-night",
    key: "animation.sagradaNight",
    value: "app.animation.sagrada_ending",
    slash: "sagrada-ending",
  },
  {
    family: "Corcovado",
    ending: false,
    style: "corcovado-day",
    key: "animation.corcovadoDay",
    value: "app.animation.corcovado",
    slash: "corcovado",
  },
  {
    family: "Corcovado",
    ending: true,
    style: "corcovado-gold",
    key: "animation.corcovadoGold",
    value: "app.animation.corcovado_ending",
    slash: "corcovado-ending",
  },
  {
    family: "Eiffel Tower",
    ending: false,
    style: "eiffel-day",
    key: "animation.eiffelDay",
    value: "app.animation.eiffel",
    slash: "eiffel",
  },
  {
    family: "Eiffel Tower",
    ending: true,
    style: "eiffel-night",
    key: "animation.eiffelNight",
    value: "app.animation.eiffel_ending",
    slash: "eiffel-ending",
  },
  {
    family: "Brandenburg Gate",
    ending: false,
    style: "brandenburg-night",
    key: "animation.brandenburgNight",
    value: "app.animation.brandenburg",
    slash: "brandenburg",
  },
  {
    family: "Brandenburg Gate",
    ending: true,
    style: "brandenburg-dawn",
    key: "animation.brandenburgDawn",
    value: "app.animation.brandenburg_ending",
    slash: "brandenburg-ending",
  },
  {
    family: "Onion Domes",
    ending: false,
    style: "domes-snow",
    key: "animation.domesSnow",
    value: "app.animation.domes",
    slash: "domes",
  },
  {
    family: "Onion Domes",
    ending: true,
    style: "domes-clear",
    key: "animation.domesClear",
    value: "app.animation.domes_ending",
    slash: "domes-ending",
  },
  {
    family: "Borobudur",
    ending: false,
    style: "borobudur-mist",
    key: "animation.borobudurMist",
    value: "app.animation.borobudur",
    slash: "borobudur",
  },
  {
    family: "Borobudur",
    ending: true,
    style: "borobudur-noon",
    key: "animation.borobudurNoon",
    value: "app.animation.borobudur_ending",
    slash: "borobudur-ending",
  },
  {
    family: "Balloons",
    ending: false,
    style: "balloons-night",
    key: "animation.balloonsNight",
    value: "app.animation.balloons",
    slash: "balloons",
  },
  {
    family: "Balloons",
    ending: true,
    style: "balloons-dawn",
    key: "animation.balloonsDawn",
    value: "app.animation.balloons_ending",
    slash: "balloons-ending",
  },
  {
    family: "Mekong",
    ending: false,
    style: "mekong-dawn",
    key: "animation.mekongDawn",
    value: "app.animation.mekong",
    slash: "mekong",
  },
  {
    family: "Mekong",
    ending: true,
    style: "mekong-dusk",
    key: "animation.mekongDusk",
    value: "app.animation.mekong_ending",
    slash: "mekong-ending",
  },
  {
    family: "Colosseum",
    ending: false,
    style: "colosseum-day",
    key: "animation.colosseumDay",
    value: "app.animation.colosseum",
    slash: "colosseum",
  },
  {
    family: "Colosseum",
    ending: true,
    style: "colosseum-night",
    key: "animation.colosseumNight",
    value: "app.animation.colosseum_ending",
    slash: "colosseum-ending",
  },
  {
    family: "Space",
    ending: false,
    style: "space-launch",
    key: "animation.spaceLaunch",
    value: "app.animation.space",
    slash: "space",
  },
  {
    family: "Space",
    ending: true,
    style: "space-drift",
    key: "animation.spaceDrift",
    value: "app.animation.space_ending",
    slash: "space-ending",
  },
  {
    family: "Dungeon",
    ending: false,
    style: "dungeon-descent",
    key: "animation.dungeonDescent",
    value: "app.animation.dungeon",
    slash: "dungeon",
  },
  {
    family: "Dungeon",
    ending: true,
    style: "dungeon-treasure",
    key: "animation.dungeonTreasure",
    value: "app.animation.dungeon_ending",
    slash: "dungeon-ending",
  },
  {
    family: "Castle",
    ending: false,
    style: "castle-day",
    key: "animation.castleDay",
    value: "app.animation.castle",
    slash: "castle",
  },
  {
    family: "Castle",
    ending: true,
    style: "castle-night",
    key: "animation.castleNight",
    value: "app.animation.castle_ending",
    slash: "castle-ending",
  },
  {
    family: "Floating Islands",
    ending: false,
    style: "islands-day",
    key: "animation.islandsDay",
    value: "app.animation.islands",
    slash: "islands",
  },
  {
    family: "Floating Islands",
    ending: true,
    style: "islands-dusk",
    key: "animation.islandsDusk",
    value: "app.animation.islands_ending",
    slash: "islands-ending",
  },
  {
    family: "Jungle",
    ending: false,
    style: "jungle-day",
    key: "animation.jungleDay",
    value: "app.animation.jungle",
    slash: "jungle",
  },
  {
    family: "Jungle",
    ending: true,
    style: "jungle-night",
    key: "animation.jungleNight",
    value: "app.animation.jungle_ending",
    slash: "jungle-ending",
  },
  {
    family: "Coral Reef",
    ending: false,
    style: "reef-day",
    key: "animation.reefDay",
    value: "app.animation.reef",
    slash: "reef",
  },
  {
    family: "Coral Reef",
    ending: true,
    style: "reef-night",
    key: "animation.reefNight",
    value: "app.animation.reef_ending",
    slash: "reef-ending",
  },
  {
    family: "Pyramids",
    ending: false,
    style: "pyramids-day",
    key: "animation.pyramidsDay",
    value: "app.animation.pyramids",
    slash: "pyramids",
  },
  {
    family: "Pyramids",
    ending: true,
    style: "pyramids-night",
    key: "animation.pyramidsNight",
    value: "app.animation.pyramids_ending",
    slash: "pyramids-ending",
  },
  {
    family: "Aurora",
    ending: false,
    style: "aurora-night",
    key: "animation.auroraNight",
    value: "app.animation.aurora",
    slash: "aurora",
  },
  {
    family: "Aurora",
    ending: true,
    style: "aurora-dawn",
    key: "animation.auroraDawn",
    value: "app.animation.aurora_ending",
    slash: "aurora-ending",
  },
  {
    family: "Lighthouse",
    ending: false,
    style: "lighthouse-day",
    key: "animation.lighthouseDay",
    value: "app.animation.lighthouse",
    slash: "lighthouse",
  },
  {
    family: "Lighthouse",
    ending: true,
    style: "lighthouse-night",
    key: "animation.lighthouseNight",
    value: "app.animation.lighthouse_ending",
    slash: "lighthouse-ending",
  },
  {
    family: "Waterfall",
    ending: false,
    style: "falls-day",
    key: "animation.fallsDay",
    value: "app.animation.falls",
    slash: "falls",
  },
  {
    family: "Waterfall",
    ending: true,
    style: "falls-moon",
    key: "animation.fallsMoon",
    value: "app.animation.falls_ending",
    slash: "falls-ending",
  },
  {
    family: "Steppe",
    ending: false,
    style: "steppe-day",
    key: "animation.steppeDay",
    value: "app.animation.steppe",
    slash: "steppe",
  },
  {
    family: "Steppe",
    ending: true,
    style: "steppe-night",
    key: "animation.steppeNight",
    value: "app.animation.steppe_ending",
    slash: "steppe-ending",
  },
  {
    family: "Canyon",
    ending: false,
    style: "canyon-day",
    key: "animation.canyonDay",
    value: "app.animation.canyon",
    slash: "canyon",
  },
  {
    family: "Canyon",
    ending: true,
    style: "canyon-night",
    key: "animation.canyonNight",
    value: "app.animation.canyon_ending",
    slash: "canyon-ending",
  },
  {
    family: "Singapore",
    ending: false,
    style: "singapore-day",
    key: "animation.singaporeDay",
    value: "app.animation.singapore",
    slash: "singapore",
  },
  {
    family: "Singapore",
    ending: true,
    style: "singapore-night",
    key: "animation.singaporeNight",
    value: "app.animation.singapore_ending",
    slash: "singapore-ending",
  },
] as const

/** Named theme families remain searchable in every interface language. */
export function animationPreviewCommands(input: {
  t: Translate
  opening: (style: OverlayStyle) => void
  ending: (style: OverlayStyle) => void
}): CommandOption[] {
  return PREVIEWS.map((preview) => ({
    title:
      preview.style === "digital-code"
        ? input.t(preview.key)
        : `${input.t(preview.ending ? "command.ending" : "command.opening")} - ${input.t(preview.key)}`,
    value: preview.value,
    category: `${input.t("category.system")} - ${preview.family}`,
    slash: { name: preview.slash, hidden: true },
    onSelect: (dialog) => {
      dialog.clear()
      if (preview.ending) input.ending(preview.style)
      else input.opening(preview.style)
    },
  }))
}
