/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractSymbols(source: string, language: string): string

export declare function hasGrammar(language: string): boolean

export declare function parseBatch(filesJson: string, concurrency: number): string

export declare function supportedLanguages(): Array<string>
