//! ADR-046 Slice A — unicode width + grapheme cluster core.
//!
//! A faithful transliteration of the Zig reference's `encodeUnicode` pipeline
//! (opentui v0.4.1 `utf8.zig` + `lib.zig`), byte-for-byte including its
//! quirks, because the parity contract is the shipped binary's observable
//! output — not an idealized spec:
//!
//! - Phase 1 (`find_grapheme_info`): UAX #29 clustering over the text.
//!   unicode mode records (multibyte|tab) clusters with width > 0; wcwidth
//!   mode records ALL (multibyte|tab) clusters and its cluster width is the
//!   SUM of per-codepoint widths, while unicode mode applies the VS16 /
//!   regional-indicator / Devanagari-virama rules.
//! - Phase 2 (`encode_widths`): the encoder walk. Specials are consumed by
//!   COLUMN match (`col_offset == col`, jumping byte_offset over anything in
//!   between); non-matching bytes are consumed one at a time, where the cell
//!   width is recomputed at that byte via the Zig decoder — a continuation
//!   byte decodes through the unconditional 4-byte branch into a garbage
//!   codepoint (or U+FFFD near the end), which is how the reference emits
//!   junk cells for standalone zero-width clusters not covered by a special.
//! - The emitted wcwidth-mode cell width is the FIRST codepoint's width
//!   (`getWidthAtWCWidth`), not the cluster sum.
//!
//! Per-codepoint widths come from `width_table.rs`, GENERATED by probing the
//! shipped Zig library (`script/gen-native-render-width-table.mjs`). Parity
//! oracle: `script/native-render-unicode-parity.mjs`.

use crate::gcb::{BreakState, is_grapheme_break};
use crate::width_table::{WIDE_RANGES, ZERO_WIDTH_RANGES};
use unicode_properties::{GeneralCategory, UnicodeGeneralCategory};

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum WidthMethod {
    Wcwidth,
    Unicode,
}

impl WidthMethod {
    pub fn from_code(code: u32) -> WidthMethod {
        if code == 0 {
            WidthMethod::Wcwidth
        } else {
            WidthMethod::Unicode
        }
    }
}

fn in_ranges(ranges: &[(u32, u32)], cp: u32) -> bool {
    ranges
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// Per-codepoint cell width (the Zig `eawToWidth` clamped to >= 0).
pub fn codepoint_width(cp: u32) -> u32 {
    if cp < 0x80 {
        return if (0x20..=0x7E).contains(&cp) { 1 } else { 0 };
    }
    if cp > 0x10FFFF || in_ranges(ZERO_WIDTH_RANGES, cp) {
        return 0;
    }
    if in_ranges(WIDE_RANGES, cp) {
        return 2;
    }
    1
}

/// Zig `charWidth`: width of a codepoint given its first byte, with tabs.
fn char_width(first_byte: u8, cp: u32, tab_width: u8) -> u32 {
    if first_byte == b'\t' {
        tab_width as u32
    } else if first_byte < 0x80 {
        if (32..=126).contains(&first_byte) {
            1
        } else {
            0
        }
    } else {
        codepoint_width(cp)
    }
}

/// Zig `decodeUtf8Unchecked`: no validation; a continuation byte falls
/// through to the 4-byte branch and produces a garbage codepoint; truncated
/// sequences at the end of the text yield U+FFFD with len 1.
fn zig_decode(bytes: &[u8], pos: usize) -> (u32, usize) {
    let b0 = bytes[pos];
    if b0 < 0x80 {
        return (b0 as u32, 1);
    }
    if pos + 1 >= bytes.len() {
        return (0xFFFD, 1);
    }
    let b1 = bytes[pos + 1] as u32;
    if (b0 & 0xE0) == 0xC0 {
        return ((((b0 & 0x1F) as u32) << 6) | (b1 & 0x3F), 2);
    }
    if pos + 2 >= bytes.len() {
        return (0xFFFD, 1);
    }
    let b2 = bytes[pos + 2] as u32;
    if (b0 & 0xF0) == 0xE0 {
        return (
            (((b0 & 0x0F) as u32) << 12) | ((b1 & 0x3F) << 6) | (b2 & 0x3F),
            3,
        );
    }
    if pos + 3 >= bytes.len() {
        return (0xFFFD, 1);
    }
    let b3 = bytes[pos + 3] as u32;
    (
        (((b0 & 0x07) as u32) << 18) | ((b1 & 0x3F) << 12) | ((b2 & 0x3F) << 6) | (b3 & 0x3F),
        4,
    )
}

/// Zig `GraphemeWidthState` — accumulates the cell width of one cluster.
struct ClusterWidth {
    width: u32,
    has_width: bool,
    is_ri_pair: bool,
    has_indic_virama: bool,
    method: WidthMethod,
}

const fn is_ri(cp: u32) -> bool {
    cp >= 0x1F1E6 && cp <= 0x1F1FF
}

impl ClusterWidth {
    fn init(first_cp: u32, first_width: u32, method: WidthMethod) -> ClusterWidth {
        ClusterWidth {
            width: first_width,
            has_width: first_width > 0,
            is_ri_pair: is_ri(first_cp),
            has_indic_virama: false,
            method,
        }
    }

    fn add(&mut self, cp: u32, cp_width: u32) {
        if self.method == WidthMethod::Wcwidth {
            let w = codepoint_width(cp);
            if w > 0 {
                self.width += w;
                self.has_width = true;
            }
            return;
        }

        let is_vs16 = cp == 0xFE0F;
        let is_virama = char::from_u32(cp)
            .is_some_and(|c| c.general_category() == GeneralCategory::NonspacingMark);
        let is_devanagari_ra = cp == 0x0930;
        let is_devanagari_base = (0x0915..=0x0939).contains(&cp) || (0x0958..=0x095F).contains(&cp);

        if is_vs16 {
            if self.has_width && self.width == 1 {
                self.width = 2;
            }
            return;
        }
        if is_virama {
            self.has_indic_virama = true;
            return;
        }
        if self.is_ri_pair && is_ri(cp) {
            self.width += cp_width;
            self.has_width = true;
        } else if !self.has_width && cp_width > 0 {
            self.width = cp_width;
            self.has_width = true;
        } else if self.has_width && self.has_indic_virama && is_devanagari_base && cp_width > 0 {
            if !is_devanagari_ra {
                self.width += cp_width;
            }
            self.has_indic_virama = false;
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct GraphemeInfo {
    pub(crate) byte_offset: usize,
    pub(crate) byte_len: usize,
    pub(crate) width: u32,
    pub(crate) col_offset: u32,
}

/// Cluster boundaries of the (valid UTF-8) text, using the uucode-matching
/// state machine (`gcb.rs`). Invalid codepoints (literal U+FFFD) force breaks
/// inside `is_grapheme_break`, so they become single-codepoint clusters
/// exactly like the Zig reference.
pub(crate) fn clusters(text: &str) -> Vec<(usize, usize)> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut state = BreakState::default();
    let mut prev: Option<u32> = None;
    let mut cluster_start = 0usize;
    let mut pos = 0usize;
    while pos < bytes.len() {
        let (cp, len) = zig_decode(bytes, pos);
        if is_grapheme_break(prev, cp, &mut state) && prev.is_some() {
            out.push((cluster_start, pos - cluster_start));
            cluster_start = pos;
        }
        prev = Some(cp);
        pos += len;
    }
    if prev.is_some() {
        out.push((cluster_start, bytes.len() - cluster_start));
    }
    out
}

pub(crate) fn cluster_width_of(
    text: &str,
    start: usize,
    len: usize,
    method: WidthMethod,
    tab_width: u8,
) -> u32 {
    let bytes = &text.as_bytes()[start..start + len];
    let s = &text[start..start + len];
    let mut chars = s.chars();
    let first = chars.next().expect("non-empty cluster");
    let mut state = ClusterWidth::init(
        first as u32,
        char_width(bytes[0], first as u32, tab_width),
        method,
    );
    for ch in chars {
        state.add(ch as u32, codepoint_width(ch as u32));
    }
    state.width
}

/// Zig `isAsciiOnly`: every byte in the PRINTABLE range [32, 126] (tabs and
/// controls disqualify); empty text is not ASCII-only.
pub(crate) fn is_ascii_only(text: &str) -> bool {
    !text.is_empty() && text.bytes().all(|b| (32..=126).contains(&b))
}

/// Zig `findGraphemeInfo`: the "specials" table consumed by the encoder walk.
pub(crate) fn find_grapheme_info(
    text: &str,
    method: WidthMethod,
    tab_width: u8,
) -> Vec<GraphemeInfo> {
    let bytes = text.as_bytes();
    if is_ascii_only(text) {
        // Zig returns early for printable-ASCII-only text in both modes.
        return Vec::new();
    }
    let mut out = Vec::new();
    let mut col: u32 = 0;
    for (start, len) in clusters(text) {
        let width = cluster_width_of(text, start, len, method, tab_width);
        // Zig cluster_is_multibyte: any codepoint in the cluster is non-ASCII
        // (a CRLF cluster is two ASCII codepoints and is NOT multibyte).
        let is_multibyte = bytes[start..start + len].iter().any(|&b| b >= 0x80);
        let is_tab = bytes[start] == b'\t';
        let record = match method {
            // unicode mode: only clusters with a visible width
            WidthMethod::Unicode => (is_multibyte || is_tab) && width > 0,
            // wcwidth mode: all multibyte/tab clusters, even zero-width
            WidthMethod::Wcwidth => is_multibyte || is_tab,
        };
        if record {
            out.push(GraphemeInfo {
                byte_offset: start,
                byte_len: len,
                width,
                col_offset: col,
            });
        }
        col += width;
    }
    out
}

/// Zig `getWidthAt` for unicode mode: width of the cluster starting at an
/// arbitrary byte anchor, decoding with `zig_decode` and running the break
/// state fresh from the anchor. Invalid codepoints force breaks.
pub(crate) fn width_at_unicode(bytes: &[u8], anchor: usize, tab_width: u8) -> u32 {
    if anchor >= bytes.len() {
        return 0;
    }
    let (first_cp, first_len) = zig_decode(bytes, anchor);
    if anchor + first_len > bytes.len() {
        return 1; // Zig: truncated decode reports width 1
    }
    let first_width = char_width(bytes[anchor], first_cp, tab_width);
    let mut width = ClusterWidth::init(first_cp, first_width, WidthMethod::Unicode);
    let mut state = BreakState::default();
    let mut prev = Some(first_cp);
    let mut pos = anchor + first_len;
    while pos < bytes.len() {
        let (cp, len) = zig_decode(bytes, pos);
        if pos + len > bytes.len() {
            break;
        }
        if is_grapheme_break(prev, cp, &mut state) {
            break;
        }
        width.add(cp, codepoint_width(cp));
        prev = Some(cp);
        pos += len;
    }
    width.width
}

/// Zig `getWidthAtWCWidth`: the first codepoint's own width.
pub(crate) fn width_at_wcwidth(bytes: &[u8], anchor: usize, tab_width: u8) -> u32 {
    if anchor >= bytes.len() {
        return 0;
    }
    let (cp, len) = zig_decode(bytes, anchor);
    if bytes[anchor] >= 0x80 && anchor + len > bytes.len() {
        return 1; // Zig: truncated decode reports width 1
    }
    char_width(bytes[anchor], cp, tab_width)
}

/// Marker in `encode_widths` output when the emitted cell is not a simple
/// printable-ASCII codepoint (the Zig side stores a grapheme-pool id there,
/// which is allocation-order dependent and not comparable).
pub const SPECIAL_CHAR: u32 = 0xFFFF_FFFF;

/// Mirror of the Zig `encodeUnicode` observable output.
pub fn encode_widths(text: &str, method: WidthMethod, tab_width: u8) -> Vec<(u32, u32)> {
    let bytes = text.as_bytes();
    let specials = find_grapheme_info(text, method, tab_width);
    let mut out = Vec::new();
    let mut col: u32 = 0;
    let mut byte_offset: usize = 0;
    let mut special_idx: usize = 0;

    while byte_offset < bytes.len() {
        let at_special = special_idx < specials.len() && specials[special_idx].col_offset == col;

        let (cell_bytes_start, cell_bytes_len, g_width, anchor) = if at_special {
            let g = &specials[special_idx];
            special_idx += 1;
            byte_offset = g.byte_offset + g.byte_len;
            (g.byte_offset, g.byte_len, g.width, g.byte_offset)
        } else {
            byte_offset += 1;
            (byte_offset - 1, 1, 1, byte_offset - 1)
        };

        let cell_width = match method {
            WidthMethod::Unicode => width_at_unicode(bytes, anchor, tab_width),
            WidthMethod::Wcwidth => width_at_wcwidth(bytes, anchor, tab_width),
        };
        if cell_width == 0 {
            col += g_width;
            continue;
        }

        let char_value = if cell_bytes_len == 1 && cell_width == 1 && bytes[cell_bytes_start] >= 32
        {
            bytes[cell_bytes_start] as u32
        } else {
            SPECIAL_CHAR
        };
        out.push((cell_width, char_value));
        col += g_width;
    }
    out
}

/// Zig `calculateTextWidth`: total display width. ASCII-only text short-cuts
/// to its byte length (tabs count 1 in that path — reference quirk).
pub(crate) fn calculate_text_width(text: &str, tab_width: u8, method: WidthMethod) -> u32 {
    if text.is_empty() {
        return 0;
    }
    if is_ascii_only(text) {
        return text.len() as u32;
    }
    clusters(text)
        .iter()
        .map(|&(start, len)| cluster_width_of(text, start, len, method, tab_width))
        .sum()
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LineBreakKind {
    Lf,
    Crlf,
    Cr,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct WrapBreak {
    pub pos: u32,
    pub kind: LineBreakKind,
}

/// Zig `findLineBreaks`: newline positions. CRLF records at the LF byte and
/// consumes both; lone CR records at the CR byte. (The reference's separate
/// `findWrapBreaks` is the word-wrap boundary scanner — Slice C5.)
pub fn find_line_breaks(bytes: &[u8]) -> Vec<WrapBreak> {
    let mut out = Vec::new();
    let mut pos = 0usize;
    while pos < bytes.len() {
        match bytes[pos] {
            b'\n' => {
                let kind = if pos > 0 && bytes[pos - 1] == b'\r' {
                    LineBreakKind::Crlf
                } else {
                    LineBreakKind::Lf
                };
                out.push(WrapBreak {
                    pos: pos as u32,
                    kind,
                });
            }
            b'\r' => {
                if pos + 1 < bytes.len() && bytes[pos + 1] == b'\n' {
                    out.push(WrapBreak {
                        pos: pos as u32 + 1,
                        kind: LineBreakKind::Crlf,
                    });
                    pos += 1;
                } else {
                    out.push(WrapBreak {
                        pos: pos as u32,
                        kind: LineBreakKind::Cr,
                    });
                }
            }
            _ => {}
        }
        pos += 1;
    }
    out
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PosByWidth {
    pub byte_offset: u32,
    pub grapheme_count: u32,
    pub columns_used: u32,
}

/// Zig `findPosByWidth`: map a column limit to a byte offset, snapping to
/// grapheme cluster boundaries. `include_start_before` selects the snapping
/// direction: true includes any cluster that STARTS before the limit
/// (selection ends snap forward); false only includes clusters that END at
/// or before it (selection starts snap backward).
pub fn find_pos_by_width(
    text: &str,
    max_columns: u32,
    tab_width: u8,
    is_ascii: bool,
    include_start_before: bool,
    method: WidthMethod,
) -> PosByWidth {
    let bytes = text.as_bytes();
    if bytes.is_empty() || max_columns == 0 {
        return PosByWidth {
            byte_offset: 0,
            grapheme_count: 0,
            columns_used: 0,
        };
    }
    if is_ascii {
        let n = bytes.len() as u32;
        let cut = max_columns.min(n);
        return PosByWidth {
            byte_offset: cut,
            grapheme_count: cut,
            columns_used: cut,
        };
    }
    let mut columns_used: u32 = 0;
    let mut graphemes: u32 = 0;
    let cluster_list = clusters(text);
    let last = cluster_list.len().saturating_sub(1);
    for (idx, &(start, len)) in cluster_list.iter().enumerate() {
        let w = cluster_width_of(text, start, len, method, tab_width);
        if idx == last {
            // Zig's final-cluster flush: the trailing cluster is excluded only
            // when the columns consumed BEFORE it already reach the limit — a
            // boundary-straddling final cluster is swallowed whole and the
            // function reports text.len (reference quirk, found by fuzz).
            if w > 0 {
                if columns_used >= max_columns {
                    return PosByWidth {
                        byte_offset: start as u32,
                        grapheme_count: graphemes,
                        columns_used,
                    };
                }
                columns_used += w;
                if include_start_before {
                    graphemes += 1;
                }
            }
            break;
        }
        if include_start_before {
            if columns_used >= max_columns {
                return PosByWidth {
                    byte_offset: start as u32,
                    grapheme_count: graphemes,
                    columns_used,
                };
            }
            columns_used += w;
            graphemes += 1;
        } else {
            if columns_used + w > max_columns {
                return PosByWidth {
                    byte_offset: start as u32,
                    grapheme_count: graphemes,
                    columns_used,
                };
            }
            columns_used += w;
        }
    }
    PosByWidth {
        byte_offset: bytes.len() as u32,
        grapheme_count: graphemes,
        columns_used,
    }
}

// --- word wrap support (C5c) --------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq)]
enum WordClass {
    AsciiWord,
    CjkWord,
    Other,
}

fn is_cjk_word_codepoint(cp: u32) -> bool {
    matches!(cp,
        0x3400..=0x4DBF | 0x4E00..=0x9FFF | 0xF900..=0xFAFF |
        0x20000..=0x2A6DF | 0x2A700..=0x2B73F | 0x2B740..=0x2B81F |
        0x2B820..=0x2CEAF | 0x2CEB0..=0x2EBEF | 0x2EBF0..=0x2EE5D |
        0x2F800..=0x2FA1F | 0x3040..=0x309F | 0x30A0..=0x30FF |
        0x31F0..=0x31FF | 0xFF66..=0xFF9D | 0x1100..=0x11FF |
        0x3130..=0x318F | 0xA960..=0xA97F | 0xAC00..=0xD7AF | 0xD7B0..=0xD7FF)
}

fn classify_word_class(cp: u32) -> WordClass {
    if cp <= 0x7F {
        let b = cp as u8;
        if b.is_ascii_alphanumeric() || b == b'_' {
            WordClass::AsciiWord
        } else {
            WordClass::Other
        }
    } else if is_cjk_word_codepoint(cp) {
        WordClass::CjkWord
    } else {
        WordClass::Other
    }
}

fn is_ascii_wrap_break(b: u8) -> bool {
    matches!(
        b,
        b' ' | b'\t'
            | b'-'
            | b'/'
            | b'\\'
            | b'.'
            | b','
            | b';'
            | b':'
            | b'!'
            | b'?'
            | b'('
            | b')'
            | b'['
            | b']'
            | b'{'
            | b'}'
    )
}

fn is_unicode_wrap_break(cp: u32) -> bool {
    matches!(
        cp,
        0x00A0 | 0x1680 | 0x2000
            ..=0x200A
                | 0x202F
                | 0x205F
                | 0x3000
                | 0x200B
                | 0x00AD
                | 0x2010
                | 0x3001
                | 0x3002
                | 0xFF01
                | 0xFF0C
                | 0xFF1A
                | 0xFF1F
    )
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct WordWrapBreak {
    pub byte_offset: u32,
    /// Grapheme-cluster index of the break opportunity.
    pub char_offset: u32,
}

/// Zig `findWrapBreaks`: word-wrap break opportunities — whitespace/dash/
/// slash/punctuation/bracket delimiters (recorded AT the delimiter) plus
/// CJK<->ASCII word-class transitions (recorded at the LAST grapheme of the
/// previous run). char_offset advances once per grapheme cluster.
pub fn find_word_wrap_breaks(bytes: &[u8]) -> Vec<WordWrapBreak> {
    let mut out = Vec::new();
    let mut state = BreakState::default();
    let mut prev: Option<u32> = None;
    let mut char_offset: u32 = 0;
    let mut have_grapheme = false;
    let mut g_byte: u32 = 0;
    let mut g_char: u32 = 0;
    let mut g_class = WordClass::Other;
    let mut pos = 0usize;
    while pos < bytes.len() {
        let (cp, len) = zig_decode(bytes, pos);
        let is_break = if cp == 0xFFFD || cp > 0x10FFFF {
            true
        } else {
            match prev {
                Some(p) if p != 0xFFFD && p <= 0x10FFFF => {
                    is_grapheme_break(Some(p), cp, &mut state)
                }
                Some(_) => true,
                None => true,
            }
        };
        if is_break {
            let class = classify_word_class(cp);
            if have_grapheme
                && ((g_class == WordClass::CjkWord && class == WordClass::AsciiWord)
                    || (g_class == WordClass::AsciiWord && class == WordClass::CjkWord))
            {
                out.push(WordWrapBreak {
                    byte_offset: g_byte,
                    char_offset: g_char,
                });
            }
            have_grapheme = true;
            g_byte = pos as u32;
            g_char = char_offset;
            g_class = class;
        }
        let delim = if cp < 0x80 {
            is_ascii_wrap_break(cp as u8)
        } else {
            is_unicode_wrap_break(cp)
        };
        if delim {
            out.push(WordWrapBreak {
                byte_offset: pos as u32,
                char_offset,
            });
        }
        if is_break {
            char_offset += 1;
        }
        prev = Some(cp);
        pos += len;
    }
    out
}

/// Zig `findWrapPosByWidth`: how many whole clusters fit within max_columns
/// (uniform rule for interior AND trailing clusters, unlike findPosByWidth).
pub fn find_wrap_pos_by_width(
    text: &[u8],
    max_columns: u32,
    tab_width: u8,
    is_ascii: bool,
    method: WidthMethod,
) -> PosByWidth {
    if text.is_empty() || max_columns == 0 {
        return PosByWidth {
            byte_offset: 0,
            grapheme_count: 0,
            columns_used: 0,
        };
    }
    if is_ascii {
        let n = text.len() as u32;
        let cut = max_columns.min(n);
        return PosByWidth {
            byte_offset: cut,
            grapheme_count: cut,
            columns_used: cut,
        };
    }
    let s = std::str::from_utf8(text).unwrap_or("");
    let mut columns_used: u32 = 0;
    let mut graphemes: u32 = 0;
    for (start, len) in clusters(s) {
        let w = cluster_width_of(s, start, len, method, tab_width);
        if columns_used + w > max_columns {
            return PosByWidth {
                byte_offset: start as u32,
                grapheme_count: graphemes,
                columns_used,
            };
        }
        columns_used += w;
        graphemes += 1;
    }
    PosByWidth {
        byte_offset: text.len() as u32,
        grapheme_count: graphemes,
        columns_used,
    }
}

/// Zig iterators `charOffsetToColumn`: translate a grapheme index into a
/// column using the chunk's special-cluster table (stateful across calls —
/// grapheme_idx/col_delta persist while walking one chunk's breaks in order).
pub fn char_offset_to_column(
    char_offset: u32,
    graphemes: &[GraphemeInfo],
    grapheme_idx: &mut usize,
    col_delta: &mut i64,
) -> (u32, u32) {
    while *grapheme_idx < graphemes.len() {
        let info = &graphemes[*grapheme_idx];
        let info_char_offset = info.col_offset as i64 - *col_delta;
        if info_char_offset >= char_offset as i64 {
            break;
        }
        *col_delta += info.width as i64 - 1;
        *grapheme_idx += 1;
    }
    let break_col = (char_offset as i64 + *col_delta).max(0) as u32;
    let mut width: u32 = 1;
    if *grapheme_idx < graphemes.len() {
        let info = &graphemes[*grapheme_idx];
        if info.col_offset as i64 - *col_delta == char_offset as i64 {
            width = info.width;
        }
    }
    (break_col, width)
}

// --- editor width helpers (Slice D) -------------------------------------------

/// Zig `getWidthAt`: cell width of the grapheme cluster starting at
/// `byte_offset` within `text`.
pub fn width_at(text: &str, byte_offset: usize, tab_width: u8, method: WidthMethod) -> u32 {
    let bytes = text.as_bytes();
    if byte_offset >= bytes.len() {
        return 0;
    }
    for (start, len) in clusters(text) {
        if start == byte_offset {
            return cluster_width_of(text, start, len, method, tab_width);
        }
        if start > byte_offset {
            break;
        }
    }
    // byte_offset not on a cluster boundary: fall back to the first codepoint's width
    let (cp, _) = zig_decode(bytes, byte_offset);
    char_width(bytes[byte_offset], cp, tab_width)
}

/// Zig `getPrevGraphemeStart`: width of the last grapheme cluster ending at
/// `byte_len` (i.e. the cluster whose end is the end of the slice).
pub fn prev_grapheme_width(text: &str, byte_len: usize, tab_width: u8, method: WidthMethod) -> u32 {
    if byte_len == 0 {
        return 0;
    }
    let sub = &text[..byte_len.min(text.len())];
    let mut last: Option<(usize, usize)> = None;
    for (start, len) in clusters(sub) {
        last = Some((start, len));
    }
    match last {
        Some((start, len)) => cluster_width_of(sub, start, len, method, tab_width),
        None => 0,
    }
}

/// Zig `isWordCodepoint`: ascii-word or CJK-word class.
pub fn is_word_codepoint(cp: u32) -> bool {
    classify_word_class(cp) != WordClass::Other
}

/// Public wrapper over the reference's unchecked UTF-8 decode.
pub fn decode_at(bytes: &[u8], pos: usize) -> (u32, usize) {
    zig_decode(bytes, pos)
}
