//! ADR-046 Slice A — unicode width + grapheme cluster core.
//!
//! A faithful transliteration of the Zig reference's `encodeUnicode` pipeline
//! (opentui v0.4.1 `utf8.zig` + `lib.zig`), byte-for-byte including its
//! quirks, because the parity contract is the shipped binary's observable
//! output — not an idealized spec:
//!
//! - Phase 1 (`find_grapheme_info`): UAX #29 clustering over the text.
//!   unicode mode records (multibyte|tab) clusters with width > 0; wcwidth
//!   mode records ALL (multibyte|tab) clusters and its cluster width is the
//!   SUM of per-codepoint widths, while unicode mode applies the VS16 /
//!   regional-indicator / Devanagari-virama rules.
//! - Phase 2 (`encode_widths`): the encoder walk. Specials are consumed by
//!   COLUMN match (`col_offset == col`, jumping byte_offset over anything in
//!   between); non-matching bytes are consumed one at a time, where the cell
//!   width is recomputed at that byte via the Zig decoder — a continuation
//!   byte decodes through the unconditional 4-byte branch into a garbage
//!   codepoint (or U+FFFD near the end), which is how the reference emits
//!   junk cells for standalone zero-width clusters not covered by a special.
//! - The emitted wcwidth-mode cell width is the FIRST codepoint's width
//!   (`getWidthAtWCWidth`), not the cluster sum.
//!
//! Per-codepoint widths come from `width_table.rs`, GENERATED by probing the
//! shipped Zig library (`script/gen-native-render-width-table.mjs`). Parity
//! oracle: `script/native-render-unicode-parity.mjs`.

use crate::gcb::{BreakState, is_grapheme_break};
use crate::width_table::{WIDE_RANGES, ZERO_WIDTH_RANGES};
use unicode_properties::{GeneralCategory, UnicodeGeneralCategory};

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum WidthMethod {
    Wcwidth,
    Unicode,
}

impl WidthMethod {
    pub fn from_code(code: u32) -> WidthMethod {
        if code == 0 {
            WidthMethod::Wcwidth
        } else {
            WidthMethod::Unicode
        }
    }
}

fn in_ranges(ranges: &[(u32, u32)], cp: u32) -> bool {
    ranges
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// Per-codepoint cell width (the Zig `eawToWidth` clamped to >= 0).
pub fn codepoint_width(cp: u32) -> u32 {
    if cp < 0x80 {
        return if (0x20..=0x7E).contains(&cp) { 1 } else { 0 };
    }
    if cp > 0x10FFFF || in_ranges(ZERO_WIDTH_RANGES, cp) {
        return 0;
    }
    if in_ranges(WIDE_RANGES, cp) {
        return 2;
    }
    1
}

/// Zig `charWidth`: width of a codepoint given its first byte, with tabs.
fn char_width(first_byte: u8, cp: u32, tab_width: u8) -> u32 {
    if first_byte == b'\t' {
        tab_width as u32
    } else if first_byte < 0x80 {
        if (32..=126).contains(&first_byte) {
            1
        } else {
            0
        }
    } else {
        codepoint_width(cp)
    }
}

/// Zig `decodeUtf8Unchecked`: no validation; a continuation byte falls
/// through to the 4-byte branch and produces a garbage codepoint; truncated
/// sequences at the end of the text yield U+FFFD with len 1.
fn zig_decode(bytes: &[u8], pos: usize) -> (u32, usize) {
    let b0 = bytes[pos];
    if b0 < 0x80 {
        return (b0 as u32, 1);
    }
    if pos + 1 >= bytes.len() {
        return (0xFFFD, 1);
    }
    let b1 = bytes[pos + 1] as u32;
    if (b0 & 0xE0) == 0xC0 {
        return ((((b0 & 0x1F) as u32) << 6) | (b1 & 0x3F), 2);
    }
    if pos + 2 >= bytes.len() {
        return (0xFFFD, 1);
    }
    let b2 = bytes[pos + 2] as u32;
    if (b0 & 0xF0) == 0xE0 {
        return (
            (((b0 & 0x0F) as u32) << 12) | ((b1 & 0x3F) << 6) | (b2 & 0x3F),
            3,
        );
    }
    if pos + 3 >= bytes.len() {
        return (0xFFFD, 1);
    }
    let b3 = bytes[pos + 3] as u32;
    (
        (((b0 & 0x07) as u32) << 18) | ((b1 & 0x3F) << 12) | ((b2 & 0x3F) << 6) | (b3 & 0x3F),
        4,
    )
}

/// Zig `GraphemeWidthState` — accumulates the cell width of one cluster.
struct ClusterWidth {
    width: u32,
    has_width: bool,
    is_ri_pair: bool,
    has_indic_virama: bool,
    method: WidthMethod,
}

const fn is_ri(cp: u32) -> bool {
    cp >= 0x1F1E6 && cp <= 0x1F1FF
}

impl ClusterWidth {
    fn init(first_cp: u32, first_width: u32, method: WidthMethod) -> ClusterWidth {
        ClusterWidth {
            width: first_width,
            has_width: first_width > 0,
            is_ri_pair: is_ri(first_cp),
            has_indic_virama: false,
            method,
        }
    }

    fn add(&mut self, cp: u32, cp_width: u32) {
        if self.method == WidthMethod::Wcwidth {
            let w = codepoint_width(cp);
            if w > 0 {
                self.width += w;
                self.has_width = true;
            }
            return;
        }

        let is_vs16 = cp == 0xFE0F;
        let is_virama = char::from_u32(cp)
            .is_some_and(|c| c.general_category() == GeneralCategory::NonspacingMark);
        let is_devanagari_ra = cp == 0x0930;
        let is_devanagari_base = (0x0915..=0x0939).contains(&cp) || (0x0958..=0x095F).contains(&cp);

        if is_vs16 {
            if self.has_width && self.width == 1 {
                self.width = 2;
            }
            return;
        }
        if is_virama {
            self.has_indic_virama = true;
            return;
        }
        if self.is_ri_pair && is_ri(cp) {
            self.width += cp_width;
            self.has_width = true;
        } else if !self.has_width && cp_width > 0 {
            self.width = cp_width;
            self.has_width = true;
        } else if self.has_width && self.has_indic_virama && is_devanagari_base && cp_width > 0 {
            if !is_devanagari_ra {
                self.width += cp_width;
            }
            self.has_indic_virama = false;
        }
    }
}

struct GraphemeInfo {
    byte_offset: usize,
    byte_len: usize,
    width: u32,
    col_offset: u32,
}

/// Cluster boundaries of the (valid UTF-8) text, using the uucode-matching
/// state machine (`gcb.rs`). Invalid codepoints (literal U+FFFD) force breaks
/// inside `is_grapheme_break`, so they become single-codepoint clusters
/// exactly like the Zig reference.
fn clusters(text: &str) -> Vec<(usize, usize)> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut state = BreakState::default();
    let mut prev: Option<u32> = None;
    let mut cluster_start = 0usize;
    let mut pos = 0usize;
    while pos < bytes.len() {
        let (cp, len) = zig_decode(bytes, pos);
        if is_grapheme_break(prev, cp, &mut state) && prev.is_some() {
            out.push((cluster_start, pos - cluster_start));
            cluster_start = pos;
        }
        prev = Some(cp);
        pos += len;
    }
    if prev.is_some() {
        out.push((cluster_start, bytes.len() - cluster_start));
    }
    out
}

fn cluster_width_of(
    text: &str,
    start: usize,
    len: usize,
    method: WidthMethod,
    tab_width: u8,
) -> u32 {
    let bytes = &text.as_bytes()[start..start + len];
    let s = &text[start..start + len];
    let mut chars = s.chars();
    let first = chars.next().expect("non-empty cluster");
    let mut state = ClusterWidth::init(
        first as u32,
        char_width(bytes[0], first as u32, tab_width),
        method,
    );
    for ch in chars {
        state.add(ch as u32, codepoint_width(ch as u32));
    }
    state.width
}

/// Zig `findGraphemeInfo`: the "specials" table consumed by the encoder walk.
fn find_grapheme_info(text: &str, method: WidthMethod, tab_width: u8) -> Vec<GraphemeInfo> {
    let bytes = text.as_bytes();
    if bytes.iter().all(|&b| b < 0x80) {
        // Zig returns early for ASCII-only text in both modes.
        return Vec::new();
    }
    let mut out = Vec::new();
    let mut col: u32 = 0;
    for (start, len) in clusters(text) {
        let width = cluster_width_of(text, start, len, method, tab_width);
        // Zig cluster_is_multibyte: any codepoint in the cluster is non-ASCII
        // (a CRLF cluster is two ASCII codepoints and is NOT multibyte).
        let is_multibyte = bytes[start..start + len].iter().any(|&b| b >= 0x80);
        let is_tab = bytes[start] == b'\t';
        let record = match method {
            // unicode mode: only clusters with a visible width
            WidthMethod::Unicode => (is_multibyte || is_tab) && width > 0,
            // wcwidth mode: all multibyte/tab clusters, even zero-width
            WidthMethod::Wcwidth => is_multibyte || is_tab,
        };
        if record {
            out.push(GraphemeInfo {
                byte_offset: start,
                byte_len: len,
                width,
                col_offset: col,
            });
        }
        col += width;
    }
    out
}

/// Zig `getWidthAt` for unicode mode: width of the cluster starting at an
/// arbitrary byte anchor, decoding with `zig_decode` and running the break
/// state fresh from the anchor. Invalid codepoints force breaks.
fn width_at_unicode(bytes: &[u8], anchor: usize, tab_width: u8) -> u32 {
    if anchor >= bytes.len() {
        return 0;
    }
    let (first_cp, first_len) = zig_decode(bytes, anchor);
    if anchor + first_len > bytes.len() {
        return 1; // Zig: truncated decode reports width 1
    }
    let first_width = char_width(bytes[anchor], first_cp, tab_width);
    let mut width = ClusterWidth::init(first_cp, first_width, WidthMethod::Unicode);
    let mut state = BreakState::default();
    let mut prev = Some(first_cp);
    let mut pos = anchor + first_len;
    while pos < bytes.len() {
        let (cp, len) = zig_decode(bytes, pos);
        if pos + len > bytes.len() {
            break;
        }
        if is_grapheme_break(prev, cp, &mut state) {
            break;
        }
        width.add(cp, codepoint_width(cp));
        prev = Some(cp);
        pos += len;
    }
    width.width
}

/// Zig `getWidthAtWCWidth`: the first codepoint's own width.
fn width_at_wcwidth(bytes: &[u8], anchor: usize, tab_width: u8) -> u32 {
    if anchor >= bytes.len() {
        return 0;
    }
    let (cp, len) = zig_decode(bytes, anchor);
    if bytes[anchor] >= 0x80 && anchor + len > bytes.len() {
        return 1; // Zig: truncated decode reports width 1
    }
    char_width(bytes[anchor], cp, tab_width)
}

/// Marker in `encode_widths` output when the emitted cell is not a simple
/// printable-ASCII codepoint (the Zig side stores a grapheme-pool id there,
/// which is allocation-order dependent and not comparable).
pub const SPECIAL_CHAR: u32 = 0xFFFF_FFFF;

/// Mirror of the Zig `encodeUnicode` observable output.
pub fn encode_widths(text: &str, method: WidthMethod, tab_width: u8) -> Vec<(u32, u32)> {
    let bytes = text.as_bytes();
    let specials = find_grapheme_info(text, method, tab_width);
    let mut out = Vec::new();
    let mut col: u32 = 0;
    let mut byte_offset: usize = 0;
    let mut special_idx: usize = 0;

    while byte_offset < bytes.len() {
        let at_special = special_idx < specials.len() && specials[special_idx].col_offset == col;

        let (cell_bytes_start, cell_bytes_len, g_width, anchor) = if at_special {
            let g = &specials[special_idx];
            special_idx += 1;
            byte_offset = g.byte_offset + g.byte_len;
            (g.byte_offset, g.byte_len, g.width, g.byte_offset)
        } else {
            byte_offset += 1;
            (byte_offset - 1, 1, 1, byte_offset - 1)
        };

        let cell_width = match method {
            WidthMethod::Unicode => width_at_unicode(bytes, anchor, tab_width),
            WidthMethod::Wcwidth => width_at_wcwidth(bytes, anchor, tab_width),
        };
        if cell_width == 0 {
            col += g_width;
            continue;
        }

        let char_value = if cell_bytes_len == 1 && cell_width == 1 && bytes[cell_bytes_start] >= 32
        {
            bytes[cell_bytes_start] as u32
        } else {
            SPECIAL_CHAR
        };
        out.push((cell_width, char_value));
        col += g_width;
    }
    out
}
