/** Compatibility re-exports. The public SDK owns the provider-connect taxonomy. */
export {
  CATALOG_PRIVATE_GPU_PROVIDER_IDS,
  CLI_PLAN_PROVIDER_IDS,
  CUSTOM_API_PROVIDER_OPTION_ID,
  DEDICATED_PRIVATE_GPU_PROVIDER_IDS,
  defaultProviderConnectCategory,
  LOCAL_RUNTIME_PROVIDER_IDS,
  PRIVATE_GPU_CLOUD_PROVIDER_IDS,
  PROVIDER_CONNECT_CATEGORIES,
  providerConnectCategoriesPresent,
  providerConnectCategory,
  providerConnectCategoryHint,
  providerConnectCategoryLabel,
  providerConnectCategoryMeta,
  providerConnectCategorySortKey,
  providersInConnectCategory,
  providerConnectTypeOptionDescription,
  type ProviderConnectCategory,
} from "@ax-code/sdk/provider-connect"
