import { json } from "./dre-graph-format"

export function themeScript() {
  return [
    `<script>`,
    `(function(){`,
    `  var t=localStorage.getItem('ax-theme')||'dark';`,
    `  document.documentElement.setAttribute('data-theme',t);`,
    `})()`,
    `</script>`,
  ].join("")
}

export function themeToggle() {
  return [
    `<button class="theme-btn" id="theme-btn" onclick="axToggleTheme()" title="Switch theme">☀ Light</button>`,
    `<script>`,
    `function axToggleTheme(){`,
    `  var next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';`,
    `  document.documentElement.setAttribute('data-theme',next);`,
    `  localStorage.setItem('ax-theme',next);`,
    `  var b=document.getElementById('theme-btn');`,
    `  if(b)b.textContent=next==='dark'?'☀ Light':'◑ Dark';`,
    `  if(window._reinitGraph)window._reinitGraph(next);`,
    `}`,
    `(function(){`,
    `  var t=document.documentElement.getAttribute('data-theme')||'dark';`,
    `  var b=document.getElementById('theme-btn');`,
    `  if(b)b.textContent=t==='dark'?'☀ Light':'◑ Dark';`,
    `})()`,
    `</script>`,
  ].join("")
}

export function live(input: { sessionID?: string; directory?: string }) {
  return [
    `<script>`,
    `(() => {`,
    `const cfg = ${json({
      sessionID: input.sessionID ?? null,
      directory: input.directory ?? null,
      poll:
        input.sessionID == null
          ? `/dre-graph/fingerprint${input.directory ? `?directory=${encodeURIComponent(input.directory)}` : ""}`
          : `/dre-graph/session/${input.sessionID}/fingerprint${input.directory ? `?directory=${encodeURIComponent(input.directory)}` : ""}`,
      fingerprint: null,
    })}`,
    `const session = [`,
    `  "session.created",`,
    `  "session.updated",`,
    `  "session.deleted",`,
    `  "session.diff",`,
    `  "session.error",`,
    `  "session.status",`,
    `  "session.idle",`,
    `  "session.compacted",`,
    `]`,
    `const detail = [`,
    `  "message.updated",`,
    `  "message.removed",`,
    `  "message.part.updated",`,
    `  "message.part.removed",`,
    `  "message.part.delta",`,
    `]`,
    `const allow = cfg.sessionID == null ? session : [...session, ...detail]`,
    `let seen = JSON.stringify(cfg.fingerprint)`,
    `const node = document.getElementById("live-status")`,
    `const set = (text, kind) => {`,
    `  if (!node) return`,
    `  node.textContent = text`,
    `  node.className = kind ? "live " + kind : "live"`,
    `}`,
    `const pick = (props) => props?.sessionID ?? props?.info?.id ?? props?.info?.sessionID ?? props?.message?.sessionID ?? props?.part?.sessionID ?? props?.session?.id ?? null`,
    `const same = (data) => cfg.directory == null || data?.directory === cfg.directory`,
    `const keep = (data) => {`,
    `  const payload = data?.payload`,
    `  if (!payload || !same(data)) return false`,
    `  if (payload.type === "server.connected" || payload.type === "server.heartbeat") return false`,
    `  if (payload.type === "server.instance.disposed") return true`,
    `  if (!allow.includes(payload.type)) return false`,
    `  if (cfg.sessionID == null) return true`,
    `  return pick(payload.properties ?? {}) === cfg.sessionID`,
    `}`,
    `const key = "dre-live:" + (cfg.sessionID ?? cfg.directory ?? "index")`,
    // Streaming detail events fire continuously while an agent is working; a
    // 2s reload cadence turns the page into a reload loop that also tears down
    // the SSE connection on every cycle. Lifecycle events keep the short gap so
    // completion still shows up quickly, and an earlier pull reschedules a
    // pending slower one.
    `const gap = 2000`,
    `const streamGap = 10000`,
    `let wait = 0`,
    `let waitAt = Infinity`,
    `const pull = (min = gap) => {`,
    `  const last = Number(window.sessionStorage.getItem(key) ?? "0")`,
    `  const left = Math.max(350, min - (Date.now() - last))`,
    `  const at = Date.now() + left`,
    `  if (wait && at >= waitAt) return`,
    `  if (wait) window.clearTimeout(wait)`,
    `  waitAt = at`,
    `  set("updating", "wait")`,
    `  wait = window.setTimeout(() => {`,
    `    window.sessionStorage.setItem(key, String(Date.now()))`,
    `    window.location.reload()`,
    `  }, left)`,
    `}`,
    `const sync = async () => {`,
    `  if (!cfg.poll) return`,
    `  const res = await fetch(cfg.poll, { cache: "no-store", headers: { accept: "application/json" } })`,
    `  if (!res.ok) return`,
    `  const next = JSON.stringify(await res.json())`,
    `  if (seen === "null") {`,
    `    seen = next`,
    `    return`,
    `  }`,
    `  if (next === seen) return`,
    `  pull(cfg.sessionID == null ? gap : streamGap)`,
    `}`,
    `let _liveSrc = null;`,
    `if (typeof EventSource !== "function") {`,
    `  set("manual refresh", "off")`,
    `} else {`,
    `  set("connecting", "")`,
    `  const src = new EventSource("/global/event")`,
    `  _liveSrc = src`,
    `  src.onopen = () => set("live", "sync")`,
    `  src.onerror = () => set("offline", "off")`,
    `  src.onmessage = (event) => {`,
    `    const data = JSON.parse(event.data)`,
    `    if (keep(data)) pull(detail.includes(data.payload.type) ? streamGap : gap)`,
    `  }`,
    `}`,
    `const _poll = window.setInterval(() => {`,
    `  if (document.visibilityState !== "visible") return`,
    `  sync().catch(() => {})`,
    `}, cfg.sessionID == null ? 5000 : 2000)`,
    `const _onVisible = () => {`,
    `  if (document.visibilityState !== "visible") return`,
    `  sync().catch(() => {})`,
    `}`,
    `document.addEventListener("visibilitychange", _onVisible)`,
    `window.addEventListener("beforeunload", () => {`,
    `  window.clearInterval(_poll)`,
    `  document.removeEventListener("visibilitychange", _onVisible)`,
    `  _liveSrc?.close()`,
    `}, { once: true })`,
    `sync().catch(() => {})`,
    `})()`,
    `</script>`,
  ].join("\n")
}

export function executionSummaryScript(sid: string, directory?: string) {
  return [
    `<script>`,
    `const _AGENT = {`,
    `  build:'Dev', plan:'Planner', react:'Reasoner', general:'Assistant',`,
    `  explore:'Researcher', security:'Security', architect:'Architect',`,
    `  debug:'Debugger', perf:'Perf', devops:'DevOps', test:'Tester',`,
    `};`,
    `function _agentName(n) { return _AGENT[n] || (n ? n.charAt(0).toUpperCase()+n.slice(1) : 'Agent'); }`,
    `function _fmtMs(ms) { const s=Math.round(ms/1000); return s>=60 ? Math.floor(s/60)+'m '+s%60+'s' : s+'s'; }`,
    `function _esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}`,
    `function _updateSummary(graph) {`,
    `  const el = document.getElementById('gviz-summary-status');`,
    `  const dl = document.getElementById('gviz-summary-detail');`,
    `  if (!el || !dl) return;`,
    `  const meta = graph.metadata;`,
    `  const nodes = graph.nodes || [];`,
    `  const sorted = [...nodes].sort((a,b) => a.timestamp - b.timestamp);`,
    `  const lastRoute = [...sorted].reverse().find(n => n.type === 'agent_route');`,
    `  const currentAgent = lastRoute ? lastRoute.agent : meta.agents[0];`,
    `  const pendingStep = nodes.find(n => n.type === 'step' && n.duration == null && n.status !== 'error');`,
    `  const doneSteps = nodes.filter(n => n.type === 'step' && n.duration != null).length;`,
    `  const toolCounts = {};`,
    `  for (const t of meta.tools) toolCounts[t] = (toolCounts[t]||0)+1;`,
    `  const topTools = Object.entries(toolCounts).sort((a,b)=>b[1]-a[1]).slice(0,3)`,
    `    .map(([t,c])=>c>1?t+'\u00d7'+c:t).join(', ');`,
    `  const dur = meta.duration > 0 ? _fmtMs(meta.duration) : null;`,
    `  const errBadge = meta.errors > 0 ? ' \u00b7 '+meta.errors+' error'+(meta.errors>1?'s':'') : '';`,
    `  if (nodes.length === 0) {`,
    `    el.textContent = 'Waiting for session data\u2026'; dl.textContent = '';`,
    `  } else if (pendingStep) {`,
    `    el.textContent = _agentName(currentAgent)+' \u00b7 Step '+(pendingStep.stepIndex ?? doneSteps+1)+' of '+meta.steps+' \u2014 in progress';`,
    `    dl.textContent = (topTools || 'working'+(dur?' \u00b7 '+dur+' elapsed':''));`,
    `  } else {`,
    `    const risk = meta.risk.level;`,
    `    const riskColor = {LOW:'var(--low)',MEDIUM:'var(--warn)',HIGH:'var(--high)',CRITICAL:'var(--critical)'}[risk]||'var(--muted)';`,
    `    el.textContent = 'Completed \u00b7 '+meta.steps+' step'+(meta.steps===1?'':'s')+(dur?' \u00b7 '+dur:'');`,
    `    dl.innerHTML = (topTools?_esc(topTools)+' \u00b7 ':'')+'<span style="color:'+riskColor+'">'+_esc(risk)+' risk</span>'+errBadge;`,
    `  }`,
    `}`,
    `const _sid = ${json(sid)};`,
    // The graph route scopes sessions to the request directory and 409s on a
    // cross-project mismatch, so the directory must ride along on the fetch.
    `const _dirQuery = ${json(directory ? `&directory=${encodeURIComponent(directory)}` : "")};`,
    `let _rendering = false;`,
    `let _renderQueued = false;`,
    `function _summaryUnavailable() {`,
    `  const el = document.getElementById('gviz-summary-status');`,
    `  const dl = document.getElementById('gviz-summary-detail');`,
    `  if (el) el.textContent = 'Session summary unavailable';`,
    `  if (dl) dl.textContent = '';`,
    `}`,
    `async function _renderSummary() {`,
    `  if (_rendering) { _renderQueued = true; return; }`,
    `  _rendering = true;`,
    `  try {`,
    `    const jsonRes = await fetch('/graph/' + _sid + '?format=json' + _dirQuery, { cache: 'no-store' });`,
    `    if (!jsonRes.ok) { _summaryUnavailable(); return; }`,
    `    const j = await jsonRes.json();`,
    `    if (!j || !j.data) { _summaryUnavailable(); return; }`,
    `    _updateSummary(j.data);`,
    `  } catch(e) {`,
    `    _summaryUnavailable();`,
    `  } finally {`,
    `    _rendering = false;`,
    `    if (_renderQueued) { _renderQueued = false; _renderSummary(); }`,
    `  }`,
    `}`,
    `_renderSummary();`,
    `const _refresh = window.setInterval(_renderSummary, 15000);`,
    `window.addEventListener("beforeunload", () => window.clearInterval(_refresh), { once: true });`,
    `window._reinitGraph = function() { _renderSummary(); };`,
    `</script>`,
  ].join("\n")
}
