import { describe, expect, test } from "vitest"
import { animationPreviewCommands } from "../../../src/cli/tui/component/animation-preview-commands"
import { dialogSelectFilteredOptions } from "../../../src/cli/tui/ui/dialog-select-view-model"
import { translate, LOCALES } from "../../../src/cli/tui/i18n"
import type { DialogContext } from "../../../src/cli/tui/ui/dialog"

describe("animation command palette", () => {
  test.each(LOCALES)("all thirty-six themes are searchable and actionable in %s", (locale) => {
    const calls: string[] = []
    const options = animationPreviewCommands({
      t: (key, values) => translate(locale, key, values),
      opening: (style) => {
        calls.push(`opening:${style}`)
      },
      ending: (style) => {
        calls.push(`ending:${style}`)
      },
    })
    expect(options).toHaveLength(72)
    expect(new Set(options.map((option) => option.value)).size).toBe(72)
    expect(new Set(options.map((option) => option.slash!.name)).size).toBe(72)
    expect(options.every((option) => option.slash?.hidden === true)).toBe(true)
    for (const family of [
      "Digital Code",
      "Foliage",
      "Bench",
      "Fuji Mountain",
      "Mahjong",
      "City",
      "Festival",
      "Snow",
      "Volcano",
      "Big Ben",
      "Taipei 101",
      "Great Wall",
      "Torii Gate",
      "Taegeuk",
      "Sagrada Familia",
      "Corcovado",
      "Eiffel Tower",
      "Brandenburg Gate",
      "Onion Domes",
      "Borobudur",
      "Balloons",
      "Mekong",
      "Colosseum",
      "Space",
      "Dungeon",
      "Castle",
      "Floating Islands",
      "Jungle",
      "Coral Reef",
      "Pyramids",
      "Aurora",
      "Lighthouse",
      "Waterfall",
      "Steppe",
      "Canyon",
      "Singapore",
    ]) {
      const found = dialogSelectFilteredOptions(options, family)
      for (const option of options.filter((item) => item.category!.endsWith(family))) expect(found).toContain(option)
    }
    const dialog = {
      clear: () => {
        calls.push("clear")
      },
    } as unknown as DialogContext
    for (const option of options) option.onSelect!(dialog)
    expect(calls).toEqual([
      "clear",
      "opening:digital-code",
      "clear",
      "ending:digital-code",
      "clear",
      "opening:classic-foliage",
      "clear",
      "ending:golden-foliage",
      "clear",
      "opening:midnight-dream",
      "clear",
      "ending:sunset-serenade",
      "clear",
      "opening:fuji-day",
      "clear",
      "ending:fuji-night",
      "clear",
      "opening:mahjong-match",
      "clear",
      "ending:mahjong-ending",
      "clear",
      "opening:city-night",
      "clear",
      "ending:city-dawn",
      "clear",
      "opening:festival-fireworks",
      "clear",
      "ending:festival-lanterns",
      "clear",
      "opening:snowfall",
      "clear",
      "ending:winter-night",
      "clear",
      "opening:volcano-eruption",
      "clear",
      "ending:volcano-calm",
      "clear",
      "opening:bigben-day",
      "clear",
      "ending:bigben-night",
      "clear",
      "opening:taipei101-day",
      "clear",
      "ending:taipei101-neon",
      "clear",
      "opening:greatwall-dawn",
      "clear",
      "ending:greatwall-dusk",
      "clear",
      "opening:torii-day",
      "clear",
      "ending:torii-night",
      "clear",
      "opening:taegeuk",
      "clear",
      "ending:taegeuk",
      "clear",
      "opening:sagrada-day",
      "clear",
      "ending:sagrada-night",
      "clear",
      "opening:corcovado-day",
      "clear",
      "ending:corcovado-gold",
      "clear",
      "opening:eiffel-day",
      "clear",
      "ending:eiffel-night",
      "clear",
      "opening:brandenburg-night",
      "clear",
      "ending:brandenburg-dawn",
      "clear",
      "opening:domes-snow",
      "clear",
      "ending:domes-clear",
      "clear",
      "opening:borobudur-mist",
      "clear",
      "ending:borobudur-noon",
      "clear",
      "opening:balloons-night",
      "clear",
      "ending:balloons-dawn",
      "clear",
      "opening:mekong-dawn",
      "clear",
      "ending:mekong-dusk",
      "clear",
      "opening:colosseum-day",
      "clear",
      "ending:colosseum-night",
      "clear",
      "opening:space-launch",
      "clear",
      "ending:space-drift",
      "clear",
      "opening:dungeon-descent",
      "clear",
      "ending:dungeon-treasure",
      "clear",
      "opening:castle-day",
      "clear",
      "ending:castle-night",
      "clear",
      "opening:islands-day",
      "clear",
      "ending:islands-dusk",
      "clear",
      "opening:jungle-day",
      "clear",
      "ending:jungle-night",
      "clear",
      "opening:reef-day",
      "clear",
      "ending:reef-night",
      "clear",
      "opening:pyramids-day",
      "clear",
      "ending:pyramids-night",
      "clear",
      "opening:aurora-night",
      "clear",
      "ending:aurora-dawn",
      "clear",
      "opening:lighthouse-day",
      "clear",
      "ending:lighthouse-night",
      "clear",
      "opening:falls-day",
      "clear",
      "ending:falls-moon",
      "clear",
      "opening:steppe-day",
      "clear",
      "ending:steppe-night",
      "clear",
      "opening:canyon-day",
      "clear",
      "ending:canyon-night",
      "clear",
      "opening:singapore-day",
      "clear",
      "ending:singapore-night",
    ])
  })
})
